import type { ComposeResult, Feature, FeatureContext } from './types.js';

/**
 * Resolves features in dependency order using topological sort.
 * Throws on circular or missing dependencies.
 */
export function resolveDependencies(features: Feature[]): Feature[] {
  const byName = new Map(features.map((f) => [f.name, f]));
  const resolved: Feature[] = [];
  const visited = new Set<string>();
  const visiting = new Set<string>();

  function visit(name: string, path: string[]): void {
    if (visited.has(name)) return;

    if (visiting.has(name)) {
      throw new Error(`Circular dependency detected: ${[...path, name].join(' → ')}`);
    }

    const feat = byName.get(name);
    if (!feat) {
      throw new Error(`Missing dependency: "${name}" required by "${path[path.length - 1]}"`);
    }

    visiting.add(name);

    for (const dep of feat.dependencies) {
      visit(dep, [...path, name]);
    }

    visiting.delete(name);
    visited.add(name);
    resolved.push(feat);
  }

  for (const feat of features) {
    visit(feat.name, []);
  }

  return resolved;
}

/**
 * Composes multiple features into a unified scaffold result.
 * Resolves dependencies, collects files, and merges package.json contributions.
 */
export function compose(projectName: string, features: Feature[]): ComposeResult {
  const ordered = resolveDependencies(features);
  const featureNames = ordered.map((f) => f.name);
  const featureSet = new Set(featureNames);

  const ctx: FeatureContext = {
    projectName,
    features: featureNames,
    hasFeature: (name) => featureSet.has(name),
  };

  // Collect files and detect conflicts
  const allFiles: ComposeResult['files'] = [];
  const seenPaths = new Map<string, string>();

  for (const feat of ordered) {
    const files = feat.files(ctx);
    for (const file of files) {
      const existing = seenPaths.get(file.path);
      if (existing) {
        throw new Error(
          `File path conflict: "${file.path}" generated by both "${existing}" and "${feat.name}"`,
        );
      }
      seenPaths.set(file.path, feat.name);
      allFiles.push(file);
    }
  }

  // Merge package contributions
  const dependencies: Record<string, string> = {};
  const devDependencies: Record<string, string> = {};
  const scripts: Record<string, string> = {};
  const imports: Record<string, string> = {};
  let hasImports = false;

  for (const feat of ordered) {
    if (!feat.packages) continue;
    Object.assign(dependencies, feat.packages.dependencies);
    Object.assign(devDependencies, feat.packages.devDependencies);
    Object.assign(scripts, feat.packages.scripts);
    if (feat.packages.imports) {
      Object.assign(imports, feat.packages.imports);
      hasImports = true;
    }
  }

  return {
    files: allFiles,
    packageJson: {
      dependencies,
      devDependencies,
      scripts,
      imports: hasImports ? imports : undefined,
    },
  };
}
