/**
 * Tenant Context — multi-tenant state management for Vertz apps.
 *
 * Provides TenantProvider + useTenant() for tenant switching, listing, and
 * auto-resolving the default tenant on login.
 */

import type { Result } from '@vertz/fetch';
import { type Context, createContext, type UnwrapSignals, useContext } from '../component/context';
import type { SdkMethodWithMeta } from '../form/form';
import { invalidateTenantQueries } from '../query/invalidate';
import { signal } from '../runtime/signal';
import type { Signal } from '../runtime/signal-types';
import { AuthContext } from './auth-context';

// --- Types ---

export interface TenantInfo {
  id: string;
  name: string;
  [key: string]: unknown;
}

export interface ListTenantsResponse {
  tenants: TenantInfo[];
  currentTenantId?: string;
  lastTenantId?: string;
  resolvedDefaultId?: string;
}

export interface TenantContextValue {
  tenants: Signal<TenantInfo[]>;
  currentTenantId: Signal<string | undefined>;
  lastTenantId: Signal<string | undefined>;
  resolvedDefaultId: Signal<string | undefined>;
  isLoading: Signal<boolean>;
  switchTenant: (tenantId: string) => Promise<Result<void, Error>>;
}

// --- Context ---

export const TenantContext: Context<TenantContextValue> = createContext<TenantContextValue>(
  undefined,
  '@vertz/ui::TenantContext',
);

// --- Hook ---

export function useTenant(): UnwrapSignals<TenantContextValue> {
  const ctx = useContext(TenantContext);
  if (!ctx) throw new Error('useTenant must be called within TenantProvider');
  return ctx;
}

// --- Provider props ---

export interface TenantProviderProps {
  /** SDK method to list tenants (generated by codegen). */
  listTenants: () => PromiseLike<Result<ListTenantsResponse, Error>>;
  /** SDK method to switch tenant (generated by codegen). */
  switchTenant: SdkMethodWithMeta<{ tenantId: string }, unknown>;
  /** Called after a successful tenant switch. */
  onSwitchComplete?: (tenantId: string) => void;
  children: (() => unknown) | unknown;
}

// --- Provider ---

export function TenantProvider({
  listTenants,
  switchTenant: switchTenantSdk,
  onSwitchComplete,
  children,
}: TenantProviderProps): HTMLElement {
  const authCtx = useContext(AuthContext);
  if (!authCtx) throw new Error('TenantProvider must be rendered inside AuthProvider');

  const tenantsSignal = signal<TenantInfo[]>([]);
  const currentTenantIdSignal = signal<string | undefined>(undefined);
  const lastTenantIdSignal = signal<string | undefined>(undefined);
  const resolvedDefaultIdSignal = signal<string | undefined>(undefined);
  const isLoadingSignal = signal(true);

  // Fetch tenants on mount (deferred to avoid sync fetch during construction)
  setTimeout(() => {
    void fetchTenants();
  }, 0);

  async function fetchTenants() {
    isLoadingSignal.value = true;
    const result = await listTenants();
    if (result.ok) {
      tenantsSignal.value = result.data.tenants;
      currentTenantIdSignal.value = result.data.currentTenantId;
      lastTenantIdSignal.value = result.data.lastTenantId;
      resolvedDefaultIdSignal.value = result.data.resolvedDefaultId;
    }
    isLoadingSignal.value = false;
  }

  async function doSwitchTenant(tenantId: string): Promise<Result<void, Error>> {
    const result = await switchTenantSdk({ tenantId });
    if (result.ok) {
      currentTenantIdSignal.value = tenantId;
      lastTenantIdSignal.value = tenantId;
      invalidateTenantQueries();
      onSwitchComplete?.(tenantId);
      return { ok: true, data: undefined };
    }
    return { ok: false, error: result.error };
  }

  const contextValue: TenantContextValue = {
    tenants: tenantsSignal,
    currentTenantId: currentTenantIdSignal,
    lastTenantId: lastTenantIdSignal,
    resolvedDefaultId: resolvedDefaultIdSignal,
    isLoading: isLoadingSignal,
    switchTenant: doSwitchTenant,
  };

  return TenantContext.Provider({ value: contextValue, children });
}
