/**
 * Client SDK for the Linear clone API.
 *
 * Wraps fetch() calls to entity endpoints, returning QueryDescriptors
 * for use with query() and Result types for mutations.
 *
 * In a real app, this would be generated by @vertz/codegen.
 */

import { err, FetchNetworkError, HttpError, ok } from '@vertz/errors';
import type { FetchResponse } from '@vertz/fetch';
import { createDescriptor } from '@vertz/fetch';
import type { CreateProjectBody, ListResponse, Project } from '../lib/types';

const BASE = '/api';

async function fetchJson<T>(
  method: string,
  path: string,
  body?: unknown,
): Promise<FetchResponse<T>> {
  try {
    const res = await fetch(`${BASE}${path}`, {
      method,
      headers: body ? { 'Content-Type': 'application/json' } : undefined,
      body: body ? JSON.stringify(body) : undefined,
      credentials: 'same-origin',
    });

    if (!res.ok) {
      const errorBody = await res.json().catch(() => ({ message: res.statusText }));
      return err(new HttpError(res.status, errorBody.message ?? res.statusText));
    }

    const data = await res.json();
    return ok({ data: data as T, status: res.status, headers: res.headers });
  } catch (e) {
    return err(new FetchNetworkError(e instanceof Error ? e.message : 'Network error'));
  }
}

export const projectApi = {
  list: Object.assign(
    () =>
      createDescriptor<ListResponse<Project>>('GET', '/projects', () =>
        fetchJson<ListResponse<Project>>('GET', '/projects'),
      ),
    { url: '/api/projects', method: 'GET' as const },
  ),

  get: Object.assign(
    (id: string) =>
      createDescriptor<Project>('GET', `/projects/${id}`, () =>
        fetchJson<Project>('GET', `/projects/${id}`),
      ),
    { url: '/api/projects/:id', method: 'GET' as const },
  ),

  create: Object.assign(
    async (body: CreateProjectBody) => {
      const res = await fetchJson<Project>('POST', '/projects', body);
      if (!res.ok) return res;
      return ok(res.data.data);
    },
    { url: '/api/projects', method: 'POST' as const },
  ),

  update: async (id: string, body: Partial<CreateProjectBody>) => {
    const res = await fetchJson<Project>('PATCH', `/projects/${id}`, body);
    if (!res.ok) return res;
    return ok(res.data.data);
  },

  delete: async (id: string) => {
    const res = await fetchJson<void>('DELETE', `/projects/${id}`);
    if (!res.ok) return res;
    return ok(undefined);
  },
};
