export interface CorsConfig {
  origins?: string | string[] | boolean;
  methods?: string[];
  headers?: string[];
  credentials?: boolean;
  maxAge?: number;
  exposedHeaders?: string[];
}

// Forward declare EntityDefinition - actual type is in @vertz/server
export interface EntityDefinition {
  readonly name: string;
  readonly model: unknown;
  readonly access: Record<string, unknown>;
  readonly before: Record<string, unknown>;
  readonly after: Record<string, unknown>;
  readonly actions: Record<string, unknown>;
  readonly relations: Record<string, unknown>;
}

/**
 * An entity route entry generated by @vertz/server's route generator.
 * Core doesn't know about entity internals — it just registers these as handlers.
 */
export interface EntityRouteEntry {
  method: string;
  path: string;
  handler: (ctx: Record<string, unknown>) => Promise<Response>;
}

export interface AppConfig {
  basePath?: string;
  version?: string;
  cors?: CorsConfig;
  /** Entity definitions for auto-CRUD route generation */
  entities?: EntityDefinition[];
  /** API prefix for entity routes (default: '/api/') */
  apiPrefix?: string;
  /** Enable response schema validation in dev mode (logs warnings but doesn't break response) */
  validateResponses?: boolean;
  /** Internal: pre-built entity route handlers injected by @vertz/server */
  _entityRoutes?: EntityRouteEntry[];
  /** Internal: factory for creating DB adapters per entity (used by @vertz/server) */
  _entityDbFactory?: (entityDef: EntityDefinition) => unknown;
}
