export interface CorsConfig {
  origins?: string | string[] | boolean;
  methods?: string[];
  headers?: string[];
  credentials?: boolean;
  maxAge?: number;
  exposedHeaders?: string[];
}

// Forward declare EntityDefinition - actual type is in @vertz/server
export interface EntityDefinition {
  readonly kind?: string;
  readonly name: string;
  readonly model: unknown;
  readonly access: Record<string, unknown>;
  readonly before: Record<string, unknown>;
  readonly after: Record<string, unknown>;
  readonly actions: Record<string, unknown>;
  readonly relations: Record<string, unknown>;
}

type SchemaLike = { parse(value: unknown): { ok: boolean; data?: unknown; error?: unknown } };

/**
 * An entity route entry generated by @vertz/server's route generator.
 * Core doesn't know about entity internals — it just registers these as handlers.
 */
export interface EntityRouteEntry {
  method: string;
  path: string;
  handler: (ctx: Record<string, unknown>) => unknown;
  paramsSchema?: SchemaLike;
  bodySchema?: SchemaLike;
  /**
   * Schema used to coerce form-encoded bodies (string fields → boolean/number/etc.)
   * before the handler runs. Unlike `bodySchema`, the runtime does not enforce
   * validation against this schema — handlers remain responsible for validation.
   * Provided by route generators that want automatic form coercion without
   * duplicating validation error formatting.
   */
  coerceSchema?: SchemaLike;
  querySchema?: SchemaLike;
  headersSchema?: SchemaLike;
  responseSchema?: SchemaLike;
  errorsSchema?: Record<number, SchemaLike>;
}

export interface AppConfig {
  basePath?: string;
  version?: string;
  cors?: CorsConfig;
  /** Entity definitions for auto-CRUD route generation */
  entities?: EntityDefinition[];
  /**
   * API prefix for entity, service, and agent routes.
   * @default '/api'
   *
   * In full-stack mode (when a UI entry is detected), an empty prefix is not
   * allowed — the dev server and Cloudflare adapter will throw a startup error.
   * For API-only apps, set to '' to serve routes at the root.
   */
  apiPrefix?: string;
  /** Enable response schema validation in dev mode (logs warnings but doesn't break response) */
  validateResponses?: boolean;
  /** Internal: pre-built entity route handlers injected by @vertz/server */
  _entityRoutes?: EntityRouteEntry[];
  /** Internal: factory for creating DB adapters per entity (used by @vertz/server) */
  _entityDbFactory?: (entityDef: EntityDefinition) => unknown;
}
