plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/matheuspoleza/Workspace/Vertz/vertz/packages/mint-docs/packages/mint-docs"
publishOrigin = "default"
base = "/Users/matheuspoleza/Workspace/Vertz/vertz/packages/mint-docs"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]