import type { ParseContext } from '../core/parse-context';
import { Schema } from '../core/schema';
import { SchemaType } from '../core/types';
import type { JSONSchemaObject, RefTracker } from '../introspection/json-schema';
export declare class StringSchema extends Schema<string> {
  private _min;
  private _minMessage;
  private _max;
  private _maxMessage;
  private _length;
  private _lengthMessage;
  private _regex;
  private _startsWith;
  private _endsWith;
  private _includes;
  private _uppercase;
  private _lowercase;
  private _trim;
  private _toLowerCase;
  private _toUpperCase;
  private _normalize;
  _parse(value: unknown, ctx: ParseContext): string;
  min(n: number, message?: string): this;
  max(n: number, message?: string): this;
  length(n: number, message?: string): this;
  regex(pattern: RegExp): this;
  startsWith(prefix: string): this;
  endsWith(suffix: string): this;
  includes(substring: string): this;
  uppercase(): this;
  lowercase(): this;
  trim(): this;
  toLowerCase(): this;
  toUpperCase(): this;
  normalize(): this;
  _schemaType(): SchemaType;
  _toJSONSchema(_tracker: RefTracker): JSONSchemaObject;
  _clone(): this;
}
//# sourceMappingURL=string.d.ts.map
