import type { ParsedResource } from '../parser/types';
import type { GeneratedFile } from './types';

/**
 * Generate the main client.ts file.
 * Uses @vertz/fetch FetchClient instead of hand-rolling HTTP methods.
 */
export function generateClient(
  resources: ParsedResource[],
  config: { baseURL?: string },
): GeneratedFile {
  const defaultBaseURL = config.baseURL ? `'${config.baseURL.replace(/'/g, "\\'")}'` : "''";
  const lines: string[] = [];

  lines.push('// Generated by @vertz/openapi — do not edit');
  lines.push('');

  // FetchClient import
  lines.push("import { FetchClient } from '@vertz/fetch';");
  lines.push("import type { FetchClientConfig } from '@vertz/fetch';");

  // Resource imports
  for (const r of resources) {
    lines.push(`import { create${r.name}Resource } from './resources/${r.identifier}';`);
  }
  lines.push('');

  // ClientOptions as alias for FetchClientConfig
  lines.push('export type ClientOptions = FetchClientConfig;');
  lines.push('');

  // createClient factory
  lines.push('export function createClient(options: ClientOptions = {}) {');
  lines.push(`  const client = new FetchClient({`);
  lines.push(`    baseURL: ${defaultBaseURL},`);
  lines.push('    ...options,');
  lines.push('  });');
  lines.push('');

  // Compose resources
  lines.push('  return {');
  for (const r of resources) {
    lines.push(`    ${r.identifier}: create${r.name}Resource(client),`);
  }
  lines.push('  };');
  lines.push('}');
  lines.push('');

  // Client type
  lines.push('export type Client = ReturnType<typeof createClient>;');
  lines.push('');

  return { path: 'client.ts', content: lines.join('\n') };
}
