import type { ParsedResource } from '../parser/types';
import type { GeneratedFile } from './types';

/**
 * Generate the main client.ts file.
 */
export function generateClient(
  resources: ParsedResource[],
  config: { baseURL?: string },
): GeneratedFile {
  const defaultBaseURL = config.baseURL ? `'${config.baseURL.replace(/'/g, "\\'")}'` : "''";
  const lines: string[] = [];

  lines.push('// Generated by @vertz/openapi — do not edit');
  lines.push('');

  // Resource imports (at top of file)
  for (const r of resources) {
    lines.push(`import { create${r.name}Resource } from './resources/${r.identifier}';`);
  }
  lines.push('');

  // HttpClient interface
  lines.push('export interface HttpClient {');
  lines.push('  get<T>(path: string, options?: { query?: Record<string, unknown> }): Promise<T>;');
  lines.push(
    '  post<T>(path: string, body?: unknown, options?: { query?: Record<string, unknown> }): Promise<T>;',
  );
  lines.push(
    '  put<T>(path: string, body?: unknown, options?: { query?: Record<string, unknown> }): Promise<T>;',
  );
  lines.push(
    '  patch<T>(path: string, body?: unknown, options?: { query?: Record<string, unknown> }): Promise<T>;',
  );
  lines.push(
    '  delete<T>(path: string, options?: { query?: Record<string, unknown> }): Promise<T>;',
  );
  lines.push('}');
  lines.push('');

  // ClientOptions
  lines.push('export interface ClientOptions {');
  lines.push('  baseURL?: string;');
  lines.push('  headers?: Record<string, string>;');
  lines.push('  fetch?: typeof globalThis.fetch;');
  lines.push('}');
  lines.push('');

  // createClient factory
  lines.push('export function createClient(options: ClientOptions = {}) {');
  lines.push(`  const baseURL = (options.baseURL ?? ${defaultBaseURL}).replace(/\\/$/, '');`);
  lines.push('  const customFetch = options.fetch ?? globalThis.fetch.bind(globalThis);');
  lines.push('  const defaultHeaders = options.headers ?? {};');
  lines.push('');

  // HttpClient implementation
  lines.push('  const client: HttpClient = {');

  // GET
  lines.push(
    '    async get<T>(path: string, opts?: { query?: Record<string, unknown> }): Promise<T> {',
  );
  lines.push('      let url = `${baseURL}${path}`;');
  lines.push('      if (opts?.query) {');
  lines.push('        const params = new URLSearchParams();');
  lines.push(
    '        for (const [k, v] of Object.entries(opts.query)) { if (v != null) params.set(k, String(v)); }',
  );
  lines.push('        const qs = params.toString();');
  lines.push('        if (qs) url += `?${qs}`;');
  lines.push('      }');
  lines.push(
    "      const res = await customFetch(url, { method: 'GET', headers: defaultHeaders });",
  );
  lines.push('      if (!res.ok) throw await ApiError.from(res);');
  lines.push('      if (res.status === 204) return undefined as T;');
  lines.push('      return res.json();');
  lines.push('    },');
  lines.push('');

  // POST, PUT, PATCH — same pattern with optional query support
  for (const method of ['post', 'put', 'patch'] as const) {
    lines.push(
      `    async ${method}<T>(path: string, body?: unknown, opts?: { query?: Record<string, unknown> }): Promise<T> {`,
    );
    lines.push(`      let url = \`\${baseURL}\${path}\`;`);
    lines.push('      if (opts?.query) {');
    lines.push('        const params = new URLSearchParams();');
    lines.push(
      '        for (const [k, v] of Object.entries(opts.query)) { if (v != null) params.set(k, String(v)); }',
    );
    lines.push('        const qs = params.toString();');
    lines.push('        if (qs) url += `?${qs}`;');
    lines.push('      }');
    lines.push(`      const res = await customFetch(url, {`);
    lines.push(`        method: '${method.toUpperCase()}',`);
    lines.push("        headers: { ...defaultHeaders, 'Content-Type': 'application/json' },");
    lines.push('        body: body !== undefined ? JSON.stringify(body) : undefined,');
    lines.push('      });');
    lines.push('      if (!res.ok) throw await ApiError.from(res);');
    lines.push('      if (res.status === 204) return undefined as T;');
    lines.push('      return res.json();');
    lines.push('    },');
    lines.push('');
  }

  // DELETE
  lines.push(
    '    async delete<T>(path: string, opts?: { query?: Record<string, unknown> }): Promise<T> {',
  );
  lines.push('      let url = `${baseURL}${path}`;');
  lines.push('      if (opts?.query) {');
  lines.push('        const params = new URLSearchParams();');
  lines.push(
    '        for (const [k, v] of Object.entries(opts.query)) { if (v != null) params.set(k, String(v)); }',
  );
  lines.push('        const qs = params.toString();');
  lines.push('        if (qs) url += `?${qs}`;');
  lines.push('      }');
  lines.push('      const res = await customFetch(url, {');
  lines.push("        method: 'DELETE',");
  lines.push('        headers: defaultHeaders,');
  lines.push('      });');
  lines.push('      if (!res.ok) throw await ApiError.from(res);');
  lines.push('      if (res.status === 204) return undefined as T;');
  lines.push('      return res.json();');
  lines.push('    },');

  lines.push('  };');
  lines.push('');

  // Compose resources
  lines.push('  return {');
  for (const r of resources) {
    lines.push(`    ${r.identifier}: create${r.name}Resource(client),`);
  }
  lines.push('  };');
  lines.push('}');
  lines.push('');

  // ApiError class
  lines.push('export class ApiError extends Error {');
  lines.push("  override name = 'ApiError';");
  lines.push('  public data: unknown;');
  lines.push('');
  lines.push('  constructor(public status: number, body: string) {');
  lines.push('    super(`API error ${status}: ${body}`);');
  lines.push('    try { this.data = JSON.parse(body); } catch { this.data = body; }');
  lines.push('  }');
  lines.push('');
  lines.push('  static async from(res: Response): Promise<ApiError> {');
  lines.push('    const body = await res.text();');
  lines.push('    return new ApiError(res.status, body);');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // Client type
  lines.push('export type Client = ReturnType<typeof createClient>;');
  lines.push('');

  return { path: 'client.ts', content: lines.join('\n') };
}
