import type { ParsedResource, ParsedSecurityScheme } from '../parser/types';
import type { GeneratedFile } from './types';

function camelCase(name: string): string {
  // Handle leading acronyms: "HTTPBearer" → "httpBearer", "APIKey" → "apiKey"
  const leadingUpper = name.match(/^[A-Z]+/);
  if (leadingUpper) {
    const prefix = leadingUpper[0];
    // If the entire string is uppercase or only one char, lowercase everything
    if (prefix.length >= name.length) return name.toLowerCase();
    // If the next char is lowercase, the acronym boundary is before the last uppercase char
    if (prefix.length > 1) {
      return prefix.slice(0, -1).toLowerCase() + name.slice(prefix.length - 1);
    }
  }
  return name.charAt(0).toLowerCase() + name.slice(1);
}

function generateAuthField(scheme: ParsedSecurityScheme): string {
  switch (scheme.type) {
    case 'bearer':
      return `  ${camelCase(scheme.name)}?: string | (() => string | Promise<string>);`;
    case 'basic':
      return `  ${camelCase(scheme.name)}?: { username: string; password: string };`;
    case 'apiKey':
      return `  ${camelCase(scheme.name)}?: string | (() => string | Promise<string>);`;
    case 'oauth2':
      return `  ${camelCase(scheme.name)}?: string | (() => string | Promise<string>);`;
  }
}

function generateAuthStrategy(scheme: ParsedSecurityScheme): string[] {
  const fieldName = camelCase(scheme.name);
  const lines: string[] = [];

  switch (scheme.type) {
    case 'bearer':
      lines.push(`    ...(options.auth?.${fieldName} ? [{`);
      lines.push(`      type: 'bearer' as const,`);
      lines.push(`      token: options.auth?.${fieldName},`);
      lines.push('    }] : []),');
      break;
    case 'basic':
      lines.push(`    ...(options.auth?.${fieldName} ? [{`);
      lines.push(`      type: 'basic' as const,`);
      lines.push(`      ...options.auth?.${fieldName},`);
      lines.push('    }] : []),');
      break;
    case 'apiKey':
      lines.push(`    ...(options.auth?.${fieldName} ? [{`);
      lines.push(`      type: 'apiKey' as const,`);
      lines.push(`      key: options.auth?.${fieldName},`);
      lines.push(`      location: '${scheme.in}' as const,`);
      lines.push(`      name: '${scheme.paramName}',`);
      lines.push('    }] : []),');
      break;
    case 'oauth2':
      lines.push(`    ...(options.auth?.${fieldName} ? [{`);
      lines.push(`      type: 'bearer' as const,`);
      lines.push(`      token: options.auth?.${fieldName},`);
      lines.push('    }] : []),');
      break;
  }

  return lines;
}

/**
 * Generate the main client.ts file.
 * Uses @vertz/fetch FetchClient instead of hand-rolling HTTP methods.
 */
export function generateClient(
  resources: ParsedResource[],
  config: { baseURL?: string; securitySchemes?: ParsedSecurityScheme[] },
): GeneratedFile {
  const defaultBaseURL = config.baseURL ? `'${config.baseURL.replace(/'/g, "\\'")}'` : "''";
  const schemes = config.securitySchemes ?? [];
  const hasAuth = schemes.length > 0;
  const lines: string[] = [];

  lines.push('// Generated by @vertz/openapi — do not edit');
  lines.push('');

  // FetchClient import
  lines.push("import { FetchClient } from '@vertz/fetch';");
  lines.push("import type { FetchClientConfig } from '@vertz/fetch';");

  // Resource imports
  for (const r of resources) {
    lines.push(`import { create${r.name}Resource } from './resources/${r.identifier}';`);
  }
  lines.push('');

  // ClientAuth interface (only when security schemes exist)
  if (hasAuth) {
    lines.push('export interface ClientAuth {');
    for (const scheme of schemes) {
      lines.push(generateAuthField(scheme));
    }
    lines.push('}');
    lines.push('');
  }

  // ClientOptions
  if (hasAuth) {
    lines.push('export type ClientOptions = FetchClientConfig & { auth?: ClientAuth };');
  } else {
    lines.push('export type ClientOptions = FetchClientConfig;');
  }
  lines.push('');

  // createClient factory
  lines.push('export function createClient(options: ClientOptions = {}) {');
  lines.push(`  const client = new FetchClient({`);
  lines.push(`    baseURL: ${defaultBaseURL},`);

  if (hasAuth) {
    lines.push('    authStrategies: [');
    for (const scheme of schemes) {
      lines.push(...generateAuthStrategy(scheme));
    }
    lines.push('    ],');
  }

  lines.push('    ...options,');
  lines.push('  });');
  lines.push('');

  // Compose resources
  lines.push('  return {');
  for (const r of resources) {
    lines.push(`    ${r.identifier}: create${r.name}Resource(client),`);
  }
  lines.push('  };');
  lines.push('}');
  lines.push('');

  // Client type
  lines.push('export type Client = ReturnType<typeof createClient>;');
  lines.push('');

  return { path: 'client.ts', content: lines.join('\n') };
}
