import { afterAll, afterEach, beforeAll, describe, expect, it, mock } from '@vertz/test';
import { PGlite } from '@electric-sql/pglite';
import { unwrap } from '@vertz/errors';
import type { MigrationQueryFn, SchemaSnapshot } from '../../migration';
import { detectSchemaDrift, migrateStatus } from '../status';

function makeSnapshot(
  tables: Record<
    string,
    Record<string, { type: string; nullable?: boolean; primary?: boolean; unique?: boolean }>
  >,
): SchemaSnapshot {
  const snap: SchemaSnapshot = { version: 1, tables: {}, enums: {} };
  for (const [tableName, cols] of Object.entries(tables)) {
    const columns: Record<
      string,
      { type: string; nullable: boolean; primary: boolean; unique: boolean }
    > = {};
    for (const [colName, col] of Object.entries(cols)) {
      columns[colName] = {
        type: col.type,
        nullable: col.nullable ?? false,
        primary: col.primary ?? false,
        unique: col.unique ?? false,
      };
    }
    snap.tables[tableName] = {
      columns,
      indexes: [],
      foreignKeys: [],
      _metadata: {},
    };
  }
  return snap;
}

describe('migrateStatus', () => {
  // One PGlite instance is shared across every test in this file. WASM init
  // is slow (hundreds of ms) and doing it per-test pushed the file past the
  // vtz test-runner's 60s per-file cap on resource-starved CI runners.
  // Tests reset state by dropping any tables they create in `afterEach`.
  let db: PGlite;
  let queryFn: MigrationQueryFn;

  beforeAll(async () => {
    db = new PGlite();
    queryFn = async (sql: string, params: readonly unknown[]) => {
      const result = await db.query(sql, params as unknown[]);
      return { rows: result.rows as Record<string, unknown>[], rowCount: result.rows.length };
    };
  });

  afterAll(async () => {
    await db.close();
  });

  afterEach(async () => {
    // Drop every user-created table + the migration history table so the next
    // test sees a fresh schema. `CASCADE` handles dependent objects (sequences
    // generated by `serial`, indexes, etc.). Listed explicitly rather than
    // introspected so that adding a new table in a test also requires updating
    // this list — deliberate visibility.
    await db.query('DROP TABLE IF EXISTS "_vertz_migrations" CASCADE');
    await db.query('DROP TABLE IF EXISTS "users" CASCADE');
    await db.query('DROP TABLE IF EXISTS "posts" CASCADE');
  });

  it('returns applied=[] and pending=[...] on a fresh database without crashing', async () => {
    const migrationFiles = [
      { name: '0001_init.sql', sql: 'CREATE TABLE users (id serial PRIMARY KEY);', timestamp: 1 },
      { name: '0002_add_email.sql', sql: 'ALTER TABLE users ADD COLUMN email text;', timestamp: 2 },
    ];

    const result = unwrap(await migrateStatus({ queryFn, migrationFiles }));

    expect(result.applied).toEqual([]);
    expect(result.pending).toEqual(['0001_init.sql', '0002_add_email.sql']);
  });

  it('returns correct status when some migrations are applied', async () => {
    await queryFn(
      `CREATE TABLE IF NOT EXISTS "_vertz_migrations" (
        "id" serial PRIMARY KEY,
        "name" text NOT NULL UNIQUE,
        "checksum" text NOT NULL,
        "applied_at" timestamp with time zone NOT NULL DEFAULT now()
      )`,
      [],
    );
    await queryFn('CREATE TABLE users (id serial PRIMARY KEY)', []);
    await queryFn(`INSERT INTO "_vertz_migrations" ("name", "checksum") VALUES ($1, $2)`, [
      '0001_init.sql',
      'abc123',
    ]);

    const migrationFiles = [
      { name: '0001_init.sql', sql: 'CREATE TABLE users (id serial PRIMARY KEY);', timestamp: 1 },
      { name: '0002_add_email.sql', sql: 'ALTER TABLE users ADD COLUMN email text;', timestamp: 2 },
    ];

    const result = unwrap(await migrateStatus({ queryFn, migrationFiles }));

    expect(result.applied).toHaveLength(1);
    expect(result.applied[0]?.name).toBe('0001_init.sql');
    expect(result.pending).toEqual(['0002_add_email.sql']);
  });

  describe('code changes detection', () => {
    it('returns empty codeChanges when snapshots match', async () => {
      const snapshot = makeSnapshot({
        users: {
          id: { type: 'integer', primary: true },
          name: { type: 'text' },
        },
      });

      const result = unwrap(
        await migrateStatus({
          queryFn,
          migrationFiles: [],
          savedSnapshot: snapshot,
          currentSnapshot: snapshot,
        }),
      );

      expect(result.codeChanges).toEqual([]);
    });

    it('detects added table in code not yet in migration', async () => {
      const savedSnapshot = makeSnapshot({
        users: { id: { type: 'integer', primary: true } },
      });
      const currentSnapshot = makeSnapshot({
        users: { id: { type: 'integer', primary: true } },
        posts: { id: { type: 'integer', primary: true } },
      });

      const result = unwrap(
        await migrateStatus({
          queryFn,
          migrationFiles: [],
          savedSnapshot,
          currentSnapshot,
        }),
      );

      expect(result.codeChanges).toHaveLength(1);
      expect(result.codeChanges[0]).toEqual({
        description: "Added table 'posts'",
        type: 'table_added',
        table: 'posts',
      });
    });

    it('detects added column in code not yet in migration', async () => {
      const savedSnapshot = makeSnapshot({
        users: { id: { type: 'integer', primary: true } },
      });
      const currentSnapshot = makeSnapshot({
        users: {
          id: { type: 'integer', primary: true },
          avatar: { type: 'text' },
        },
      });

      const result = unwrap(
        await migrateStatus({
          queryFn,
          migrationFiles: [],
          savedSnapshot,
          currentSnapshot,
        }),
      );

      expect(result.codeChanges).toHaveLength(1);
      expect(result.codeChanges[0]).toEqual({
        description: "Added column 'avatar' to table 'users'",
        type: 'column_added',
        table: 'users',
        column: 'avatar',
      });
    });

    it('returns empty codeChanges when no snapshots provided', async () => {
      const result = unwrap(
        await migrateStatus({
          queryFn,
          migrationFiles: [],
        }),
      );

      expect(result.codeChanges).toEqual([]);
    });
  });

  describe('drift detection (detectSchemaDrift)', () => {
    it('returns empty drift when schemas match', () => {
      const schema = makeSnapshot({
        users: {
          id: { type: 'integer', primary: true },
          name: { type: 'text' },
        },
      });

      const drift = detectSchemaDrift(schema, schema);

      expect(drift).toEqual([]);
    });

    it('detects extra table in database not in schema', () => {
      const expected = makeSnapshot({
        users: { id: { type: 'integer', primary: true } },
      });
      const actual = makeSnapshot({
        users: { id: { type: 'integer', primary: true } },
        temp_data: { id: { type: 'integer', primary: true } },
      });

      const drift = detectSchemaDrift(expected, actual);

      expect(drift).toHaveLength(1);
      expect(drift[0]).toEqual({
        description: "Table 'temp_data' exists in database but not in schema",
        type: 'extra_table',
        table: 'temp_data',
      });
    });

    it('detects missing table in database that exists in schema', () => {
      const expected = makeSnapshot({
        users: { id: { type: 'integer', primary: true } },
        posts: { id: { type: 'integer', primary: true } },
      });
      const actual = makeSnapshot({
        users: { id: { type: 'integer', primary: true } },
      });

      const drift = detectSchemaDrift(expected, actual);

      expect(drift).toHaveLength(1);
      expect(drift[0]).toEqual({
        description: "Table 'posts' exists in schema but not in database",
        type: 'missing_table',
        table: 'posts',
      });
    });

    it('detects extra column in database not in schema', () => {
      const expected = makeSnapshot({
        users: { id: { type: 'integer', primary: true } },
      });
      const actual = makeSnapshot({
        users: {
          id: { type: 'integer', primary: true },
          temp_flag: { type: 'boolean' },
        },
      });

      const drift = detectSchemaDrift(expected, actual);

      expect(drift).toHaveLength(1);
      expect(drift[0]).toEqual({
        description: "Column 'temp_flag' exists in database table 'users' but not in schema",
        type: 'extra_column',
        table: 'users',
        column: 'temp_flag',
      });
    });

    it('detects missing column in database that exists in schema', () => {
      const expected = makeSnapshot({
        users: {
          id: { type: 'integer', primary: true },
          email: { type: 'text' },
        },
      });
      const actual = makeSnapshot({
        users: { id: { type: 'integer', primary: true } },
      });

      const drift = detectSchemaDrift(expected, actual);

      expect(drift).toHaveLength(1);
      expect(drift[0]).toEqual({
        description: "Column 'email' exists in schema table 'users' but not in database",
        type: 'missing_column',
        table: 'users',
        column: 'email',
      });
    });

    it('detects column type mismatch', () => {
      const expected = makeSnapshot({
        users: {
          id: { type: 'integer', primary: true },
          age: { type: 'integer' },
        },
      });
      const actual = makeSnapshot({
        users: {
          id: { type: 'integer', primary: true },
          age: { type: 'text' },
        },
      });

      const drift = detectSchemaDrift(expected, actual);

      expect(drift).toHaveLength(1);
      expect(drift[0]).toEqual({
        description:
          "Column 'age' in table 'users' has type 'text' in database but 'integer' in schema",
        type: 'column_type_mismatch',
        table: 'users',
        column: 'age',
      });
    });
  });

  describe('code changes detection — all change types', () => {
    it('detects table_removed change', async () => {
      const savedSnapshot = makeSnapshot({
        users: { id: { type: 'integer', primary: true } },
        posts: { id: { type: 'integer', primary: true } },
      });
      const currentSnapshot = makeSnapshot({
        users: { id: { type: 'integer', primary: true } },
      });

      const result = unwrap(
        await migrateStatus({
          queryFn,
          migrationFiles: [],
          savedSnapshot,
          currentSnapshot,
        }),
      );

      expect(result.codeChanges).toHaveLength(1);
      expect(result.codeChanges[0]).toEqual({
        description: "Removed table 'posts'",
        type: 'table_removed',
        table: 'posts',
      });
    });

    it('detects column_removed change', async () => {
      const savedSnapshot = makeSnapshot({
        users: {
          id: { type: 'integer', primary: true },
          email: { type: 'text' },
        },
      });
      const currentSnapshot = makeSnapshot({
        users: { id: { type: 'integer', primary: true } },
      });

      const result = unwrap(
        await migrateStatus({
          queryFn,
          migrationFiles: [],
          savedSnapshot,
          currentSnapshot,
        }),
      );

      expect(result.codeChanges).toHaveLength(1);
      expect(result.codeChanges[0]).toEqual({
        description: "Removed column 'email' from table 'users'",
        type: 'column_removed',
        table: 'users',
        column: 'email',
      });
    });

    it('detects column_altered change', async () => {
      const savedSnapshot = makeSnapshot({
        users: {
          id: { type: 'integer', primary: true },
          age: { type: 'integer' },
        },
      });
      const currentSnapshot = makeSnapshot({
        users: {
          id: { type: 'integer', primary: true },
          age: { type: 'bigint' },
        },
      });

      const result = unwrap(
        await migrateStatus({
          queryFn,
          migrationFiles: [],
          savedSnapshot,
          currentSnapshot,
        }),
      );

      expect(result.codeChanges).toHaveLength(1);
      expect(result.codeChanges[0]).toEqual({
        description: "Altered column 'age' in table 'users'",
        type: 'column_altered',
        table: 'users',
        column: 'age',
      });
    });

    it('detects column_renamed change', async () => {
      const savedSnapshot = makeSnapshot({
        users: {
          id: { type: 'integer', primary: true },
          name: { type: 'text' },
        },
      });
      const currentSnapshot = makeSnapshot({
        users: {
          id: { type: 'integer', primary: true },
          fullName: { type: 'text' },
        },
      });

      const result = unwrap(
        await migrateStatus({
          queryFn,
          migrationFiles: [],
          savedSnapshot,
          currentSnapshot,
        }),
      );

      const renameChange = result.codeChanges.find((c) => c.type === 'column_renamed');
      expect(renameChange).toBeDefined();
      expect(renameChange?.description).toBe("Renamed column in table 'users'");
      expect(renameChange?.table).toBe('users');
    });

    it('detects index_added change', async () => {
      const savedSnapshot: SchemaSnapshot = {
        version: 1,
        tables: {
          users: {
            columns: {
              id: { type: 'integer', nullable: false, primary: true, unique: false },
              email: { type: 'text', nullable: false, primary: false, unique: false },
            },
            indexes: [],
            foreignKeys: [],
            _metadata: {},
          },
        },
        enums: {},
      };
      const currentSnapshot: SchemaSnapshot = {
        version: 1,
        tables: {
          users: {
            columns: {
              id: { type: 'integer', nullable: false, primary: true, unique: false },
              email: { type: 'text', nullable: false, primary: false, unique: false },
            },
            indexes: [{ columns: ['email'] }],
            foreignKeys: [],
            _metadata: {},
          },
        },
        enums: {},
      };

      const result = unwrap(
        await migrateStatus({
          queryFn,
          migrationFiles: [],
          savedSnapshot,
          currentSnapshot,
        }),
      );

      const indexChange = result.codeChanges.find((c) => c.type === 'index_added');
      expect(indexChange).toBeDefined();
      expect(indexChange?.description).toBe("Added index on table 'users'");
      expect(indexChange?.table).toBe('users');
    });

    it('detects index_removed change', async () => {
      const savedSnapshot: SchemaSnapshot = {
        version: 1,
        tables: {
          users: {
            columns: {
              id: { type: 'integer', nullable: false, primary: true, unique: false },
              email: { type: 'text', nullable: false, primary: false, unique: false },
            },
            indexes: [{ columns: ['email'] }],
            foreignKeys: [],
            _metadata: {},
          },
        },
        enums: {},
      };
      const currentSnapshot: SchemaSnapshot = {
        version: 1,
        tables: {
          users: {
            columns: {
              id: { type: 'integer', nullable: false, primary: true, unique: false },
              email: { type: 'text', nullable: false, primary: false, unique: false },
            },
            indexes: [],
            foreignKeys: [],
            _metadata: {},
          },
        },
        enums: {},
      };

      const result = unwrap(
        await migrateStatus({
          queryFn,
          migrationFiles: [],
          savedSnapshot,
          currentSnapshot,
        }),
      );

      const indexChange = result.codeChanges.find((c) => c.type === 'index_removed');
      expect(indexChange).toBeDefined();
      expect(indexChange?.description).toBe("Removed index on table 'users'");
      expect(indexChange?.table).toBe('users');
    });

    it('detects enum_added change', async () => {
      const savedSnapshot: SchemaSnapshot = { version: 1, tables: {}, enums: {} };
      const currentSnapshot: SchemaSnapshot = {
        version: 1,
        tables: {},
        enums: { role: ['admin', 'user'] },
      };

      const result = unwrap(
        await migrateStatus({
          queryFn,
          migrationFiles: [],
          savedSnapshot,
          currentSnapshot,
        }),
      );

      const enumChange = result.codeChanges.find((c) => c.type === 'enum_added');
      expect(enumChange).toBeDefined();
      expect(enumChange?.description).toBe('Added enum type');
    });

    it('detects enum_removed change', async () => {
      const savedSnapshot: SchemaSnapshot = {
        version: 1,
        tables: {},
        enums: { role: ['admin', 'user'] },
      };
      const currentSnapshot: SchemaSnapshot = { version: 1, tables: {}, enums: {} };

      const result = unwrap(
        await migrateStatus({
          queryFn,
          migrationFiles: [],
          savedSnapshot,
          currentSnapshot,
        }),
      );

      const enumChange = result.codeChanges.find((c) => c.type === 'enum_removed');
      expect(enumChange).toBeDefined();
      expect(enumChange?.description).toBe('Removed enum type');
    });

    it('detects enum_altered change', async () => {
      const savedSnapshot: SchemaSnapshot = {
        version: 1,
        tables: {},
        enums: { role: ['admin', 'user'] },
      };
      const currentSnapshot: SchemaSnapshot = {
        version: 1,
        tables: {},
        enums: { role: ['admin', 'user', 'viewer'] },
      };

      const result = unwrap(
        await migrateStatus({
          queryFn,
          migrationFiles: [],
          savedSnapshot,
          currentSnapshot,
        }),
      );

      const enumChange = result.codeChanges.find((c) => c.type === 'enum_altered');
      expect(enumChange).toBeDefined();
      expect(enumChange?.description).toBe('Altered enum type');
    });
  });

  describe('error paths', () => {
    it('returns error when createHistoryTable fails', async () => {
      const failingQueryFn: MigrationQueryFn = mock().mockImplementation(async () => {
        throw new Error('connection refused');
      });

      const result = await migrateStatus({
        queryFn: failingQueryFn,
        migrationFiles: [],
      });

      expect(result.ok).toBe(false);
    });

    it('returns error when getApplied fails', async () => {
      const failingQueryFn: MigrationQueryFn = mock().mockImplementation(async (sql: string) => {
        // First call is createHistoryTable - let it succeed
        if (sql.includes('CREATE TABLE')) {
          return { rows: [], rowCount: 0 };
        }
        // Second call is getApplied - make it fail
        throw new Error('query failed');
      });

      const result = await migrateStatus({
        queryFn: failingQueryFn,
        migrationFiles: [],
      });

      expect(result.ok).toBe(false);
    });
  });

  describe('drift detection with introspection', () => {
    it('detects drift using postgres dialect introspection', async () => {
      await queryFn(
        `CREATE TABLE IF NOT EXISTS "_vertz_migrations" (
          "id" serial PRIMARY KEY,
          "name" text NOT NULL UNIQUE,
          "checksum" text NOT NULL,
          "applied_at" timestamp with time zone NOT NULL DEFAULT now()
        )`,
        [],
      );
      await queryFn('CREATE TABLE users (id serial PRIMARY KEY, name text NOT NULL)', []);

      const expectedSnapshot = makeSnapshot({
        users: {
          id: { type: 'integer', primary: true },
          name: { type: 'text' },
          email: { type: 'text' },
        },
      });

      const result = unwrap(
        await migrateStatus({
          queryFn,
          migrationFiles: [],
          currentSnapshot: expectedSnapshot,
          dialect: {
            name: 'postgres',
            param: (n: number) => `$${n}`,
            mapColumnType: (t: string) => t,
          },
        }),
      );

      expect(result.drift).toBeDefined();
      expect(Array.isArray(result.drift)).toBe(true);
    });
  });
});
