// AUTO-GENERATED by scripts/compile-blog-posts.ts — do not edit by hand.
// Regenerated on every blog build.

import type { AuthorManifest, GeneratedPost } from '../types';
import Post_2026_04_22_hello_world from './posts/2026-04-22-hello-world.js';

export const generatedPosts: GeneratedPost[] = [
  {
    slug: "hello-world",
    wordCount: 99,
    frontmatter: {"title":"Hello, world from the Vertz blog","date":"2026-04-22","author":"matheus","description":"A tiny placeholder post so the blog pipeline has something to render during development.","slug":"hello-world","tags":["meta","dx"],"draft":false},
    Component: Post_2026_04_22_hello_world,
  },
];

export const generatedAuthors: AuthorManifest = 
  {
  "matheus": {
    "name": "Matheus Poleza",
    "avatar": "/blog/authors/matheus.jpg",
    "bio": "Building Vertz.",
    "twitter": "@matheuspoleza"
  }
};
