/**
 * Mock data and in-memory store for the Task Manager.
 *
 * In a real app, these would be SDK methods generated by @vertz/codegen
 * talking to a @vertz/core backend. Here we simulate the full CRUD cycle
 * with an in-memory array and artificial async delays.
 */
import type { CreateTaskBody, Task, UpdateTaskBody } from '../lib/types';
/** Fetch all tasks. */
export declare function fetchTasks(): Promise<{
    tasks: Task[];
    total: number;
}>;
/** Fetch a single task by ID. */
export declare function fetchTask(id: string): Promise<Task>;
/** Create a new task. Returns the created task. */
export declare function createTask(body: CreateTaskBody): Promise<Task>;
/** Update an existing task. */
export declare function updateTask(id: string, body: UpdateTaskBody): Promise<Task>;
/** Delete a task. */
export declare function deleteTask(id: string): Promise<{
    success: boolean;
}>;
/**
 * Simulated SDK methods for use with form().
 *
 * These mimic what @vertz/codegen would produce: a callable function
 * with `.url` and `.method` metadata for progressive enhancement.
 */
export declare const taskApi: {
    create: ((body: CreateTaskBody) => Promise<Task>) & {
        url: string;
        method: string;
    };
    update: (id: string) => ((body: UpdateTaskBody) => Promise<Task>) & {
        url: string;
        method: string;
    };
    delete: (id: string) => (() => Promise<{
        success: boolean;
    }>) & {
        url: string;
        method: string;
    };
};
/** Reset mock data to initial state (for tests). */
export declare function resetMockData(): void;
//# sourceMappingURL=mock-data.d.ts.map