/**
 * Mock data and in-memory store for the Task Manager.
 *
 * In a real app, these would be SDK methods generated by @vertz/codegen
 * talking to a @vertz/core backend. Here we simulate the full CRUD cycle
 * with an in-memory array and artificial async delays.
 */

import { ok } from '@vertz/errors';
import { createDescriptor } from '@vertz/fetch';
import type {
  CreateTaskBody,
  Task,
  TaskListParams,
  TaskStatus,
  UpdateTaskBody,
} from '../lib/types';

const TASK_TITLES = [
  'Set up CI/CD pipeline',
  'Implement user authentication',
  'Write API documentation',
  'Design database schema',
  'Create user dashboard',
  'Add email notifications',
  'Implement rate limiting',
  'Set up error monitoring',
  'Write unit tests for auth',
  'Configure staging environment',
  'Add password reset flow',
  'Implement file upload API',
  'Create admin panel',
  'Set up log aggregation',
  'Add WebSocket support',
  'Implement search indexing',
  'Create onboarding flow',
  'Add two-factor authentication',
  'Set up CDN for static assets',
  'Implement API versioning',
  'Create billing integration',
  'Add audit logging',
  'Implement data export',
  'Set up performance monitoring',
  'Create mobile API endpoints',
  'Add OAuth2 providers',
  'Implement caching layer',
  'Create API rate dashboard',
  'Add CORS configuration',
  'Implement webhook system',
  'Create deployment scripts',
  'Add health check endpoints',
  'Implement data migration tools',
  'Create developer documentation',
  'Add request validation middleware',
  'Implement session management',
  'Create integration test suite',
  'Add API key management',
  'Implement role-based access',
  'Create CI build notifications',
  'Add database connection pooling',
  'Implement response compression',
  'Create feature flag system',
  'Add structured logging',
  'Implement graceful shutdown',
  'Create load testing scripts',
  'Add input sanitization',
  'Implement backup automation',
  'Create API changelog',
  'Add SSL certificate automation',
];

const STATUSES: TaskStatus[] = ['todo', 'in-progress', 'done'];
const PRIORITIES: Array<'low' | 'medium' | 'high' | 'urgent'> = ['low', 'medium', 'high', 'urgent'];

function generateTasks(): Task[] {
  return TASK_TITLES.map((title, i) => ({
    id: String(i + 1),
    title,
    description: `Task ${i + 1}: ${title}. This is a detailed description of the work involved.`,
    status: STATUSES[i % STATUSES.length] as TaskStatus,
    priority: PRIORITIES[i % PRIORITIES.length] as 'low' | 'medium' | 'high' | 'urgent',
    createdAt: new Date(2026, 1, 1 + i).toISOString(),
    updatedAt: new Date(2026, 1, 2 + i).toISOString(),
  }));
}

let nextId = TASK_TITLES.length + 1;
const tasks: Task[] = generateTasks();

/** Simulate network latency. */
function delay(ms = 1000): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/** Fetch tasks with pagination. */
export async function fetchTasks(
  params: TaskListParams = {},
): Promise<{ items: Task[]; total: number; page: number; totalPages: number }> {
  await delay();
  const page = params.page ?? 1;
  const limit = params.limit ?? 10;
  const start = (page - 1) * limit;
  const items = tasks.slice(start, start + limit);
  return {
    items: items.map((t) => ({ ...t })),
    total: tasks.length,
    page,
    totalPages: Math.ceil(tasks.length / limit),
  };
}

/** Fetch a single task by ID. */
export async function fetchTask(id: string): Promise<Task> {
  await delay();
  const task = tasks.find((t) => t.id === id);
  if (!task) throw new Error(`Task ${id} not found`);
  return { ...task };
}

/** Create a new task. Returns the created task. */
export async function createTask(body: CreateTaskBody): Promise<Task> {
  await delay(300);
  const now = new Date().toISOString();
  const task: Task = {
    id: String(nextId++),
    title: body.title,
    description: body.description,
    status: 'todo',
    priority: body.priority,
    createdAt: now,
    updatedAt: now,
  };
  tasks.push(task);
  return { ...task };
}

/** Update an existing task. */
export async function updateTask(id: string, body: UpdateTaskBody): Promise<Task> {
  await delay(200);
  const idx = tasks.findIndex((t) => t.id === id);
  if (idx === -1) throw new Error(`Task ${id} not found`);
  const existing = tasks[idx] as Task;
  const updated: Task = {
    ...existing,
    ...body,
    updatedAt: new Date().toISOString(),
  };
  tasks[idx] = updated;
  return { ...updated };
}

/** Delete a task. */
export async function deleteTask(id: string): Promise<{ success: boolean }> {
  await delay(200);
  const idx = tasks.findIndex((t) => t.id === id);
  if (idx === -1) throw new Error(`Task ${id} not found`);
  tasks.splice(idx, 1);
  return { success: true };
}

/**
 * Simulated SDK using QueryDescriptor.
 *
 * This mimics what @vertz/codegen produces: each method returns a
 * QueryDescriptor that works with both query() and await.
 *
 *   const tasks = query(api.tasks.list());     // reactive
 *   const task  = await api.tasks.get('1');     // imperative
 */
function mockFetchResponse<T>(fn: () => Promise<T>) {
  return async () => ok({ data: await fn(), status: 200, headers: new Headers() });
}

export const api = {
  tasks: {
    list: Object.assign(
      (params?: TaskListParams) =>
        createDescriptor<{ items: Task[]; total: number; page: number; totalPages: number }>(
          'GET',
          '/tasks',
          mockFetchResponse(() => fetchTasks(params)),
        ),
      { url: '/tasks', method: 'GET' as const },
    ),
    get: Object.assign(
      (id: string) =>
        createDescriptor<Task>(
          'GET',
          `/tasks/${id}`,
          mockFetchResponse(() => fetchTask(id)),
        ),
      { url: '/tasks/:id', method: 'GET' as const },
    ),
    create: Object.assign(
      (body: CreateTaskBody) =>
        createDescriptor<Task>(
          'POST',
          '/tasks',
          mockFetchResponse(() => createTask(body)),
        ),
      { url: '/tasks', method: 'POST' as const },
    ),
    update: Object.assign(
      (id: string, body: UpdateTaskBody) =>
        createDescriptor<Task>(
          'PATCH',
          `/tasks/${id}`,
          mockFetchResponse(() => updateTask(id, body)),
        ),
      { url: '/tasks/:id', method: 'PATCH' as const },
    ),
    delete: Object.assign(
      (id: string) =>
        createDescriptor<{ success: boolean }>(
          'DELETE',
          `/tasks/${id}`,
          mockFetchResponse(() => deleteTask(id)),
        ),
      { url: '/tasks/:id', method: 'DELETE' as const },
    ),
  },
};

/**
 * Simulated SDK methods for use with form().
 *
 * These mimic what @vertz/codegen would produce: a callable function
 * with `.url` and `.method` metadata for progressive enhancement.
 */
export const taskApi = {
  create: Object.assign(async (body: CreateTaskBody) => ok(await createTask(body)), {
    url: '/api/tasks',
    method: 'POST',
  }),

  update: (id: string) =>
    Object.assign(async (body: UpdateTaskBody) => ok(await updateTask(id, body)), {
      url: `/api/tasks/${id}`,
      method: 'PATCH',
    }),

  delete: (id: string) =>
    Object.assign(async () => ok(await deleteTask(id)), {
      url: `/api/tasks/${id}`,
      method: 'DELETE',
    }),
};

/** Reset mock data to initial state (for tests). */
export function resetMockData(): void {
  tasks.length = 0;
  tasks.push(...generateTasks());
  nextId = TASK_TITLES.length + 1;
}
