/**
 * Mock data and in-memory store for the Task Manager.
 *
 * In a real app, these would be SDK methods generated by @vertz/codegen
 * talking to a @vertz/core backend. Here we simulate the full CRUD cycle
 * with an in-memory array and artificial async delays.
 */

import type { CreateTaskBody, Task, TaskStatus, UpdateTaskBody } from '../lib/types';

let nextId = 4;

const tasks: Task[] = [
  {
    id: '1',
    title: 'Set up CI/CD pipeline',
    description:
      'Configure GitHub Actions for automated testing and deployment. Include lint, typecheck, and test stages.',
    status: 'done',
    priority: 'high',
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-05T14:30:00Z',
  },
  {
    id: '2',
    title: 'Implement user authentication',
    description:
      'Add JWT-based auth with login, register, and token refresh endpoints. Use bcrypt for password hashing.',
    status: 'in-progress',
    priority: 'urgent',
    createdAt: '2026-02-03T09:00:00Z',
    updatedAt: '2026-02-10T16:00:00Z',
  },
  {
    id: '3',
    title: 'Write API documentation',
    description:
      'Document all REST endpoints using OpenAPI spec. Include request/response examples and error codes.',
    status: 'todo',
    priority: 'medium',
    createdAt: '2026-02-08T11:00:00Z',
    updatedAt: '2026-02-08T11:00:00Z',
  },
];

/** Simulate network latency. */
function delay(ms = 200): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/** Fetch all tasks. */
export async function fetchTasks(): Promise<{ tasks: Task[]; total: number }> {
  await delay();
  return { tasks: [...tasks], total: tasks.length };
}

/** Fetch a single task by ID. */
export async function fetchTask(id: string): Promise<Task> {
  await delay();
  const task = tasks.find((t) => t.id === id);
  if (!task) throw new Error(`Task ${id} not found`);
  return { ...task };
}

/** Create a new task. Returns the created task. */
export async function createTask(body: CreateTaskBody): Promise<Task> {
  await delay(300);
  const now = new Date().toISOString();
  const task: Task = {
    id: String(nextId++),
    title: body.title,
    description: body.description,
    status: 'todo',
    priority: body.priority,
    createdAt: now,
    updatedAt: now,
  };
  tasks.push(task);
  return { ...task };
}

/** Update an existing task. */
export async function updateTask(id: string, body: UpdateTaskBody): Promise<Task> {
  await delay(200);
  const idx = tasks.findIndex((t) => t.id === id);
  if (idx === -1) throw new Error(`Task ${id} not found`);
  const existing = tasks[idx] as Task;
  const updated: Task = {
    ...existing,
    ...body,
    updatedAt: new Date().toISOString(),
  };
  tasks[idx] = updated;
  return { ...updated };
}

/** Delete a task. */
export async function deleteTask(id: string): Promise<{ success: boolean }> {
  await delay(200);
  const idx = tasks.findIndex((t) => t.id === id);
  if (idx === -1) throw new Error(`Task ${id} not found`);
  tasks.splice(idx, 1);
  return { success: true };
}

/**
 * Simulated SDK methods for use with form().
 *
 * These mimic what @vertz/codegen would produce: a callable function
 * with `.url` and `.method` metadata for progressive enhancement.
 */
export const taskApi = {
  create: Object.assign((body: CreateTaskBody) => createTask(body), {
    url: '/api/tasks',
    method: 'POST',
  }),

  update: (id: string) =>
    Object.assign((body: UpdateTaskBody) => updateTask(id, body), {
      url: `/api/tasks/${id}`,
      method: 'PATCH',
    }),

  delete: (id: string) =>
    Object.assign(() => deleteTask(id), { url: `/api/tasks/${id}`, method: 'DELETE' }),
};

/** Reset mock data to initial state (for tests). */
export function resetMockData(): void {
  tasks.length = 0;
  tasks.push(
    {
      id: '1',
      title: 'Set up CI/CD pipeline',
      description: 'Configure GitHub Actions for automated testing and deployment.',
      status: 'done' as TaskStatus,
      priority: 'high',
      createdAt: '2026-02-01T10:00:00Z',
      updatedAt: '2026-02-05T14:30:00Z',
    },
    {
      id: '2',
      title: 'Implement user authentication',
      description: 'Add JWT-based auth with login, register, and token refresh.',
      status: 'in-progress' as TaskStatus,
      priority: 'urgent',
      createdAt: '2026-02-03T09:00:00Z',
      updatedAt: '2026-02-10T16:00:00Z',
    },
  );
  nextId = 3;
}
