/**
 * ThemeProvider — Sets `data-theme` attribute for contextual token switching.
 *
 * Creates a wrapper div element with the appropriate `data-theme` attribute
 * so that contextual CSS custom properties (generated by compileTheme) resolve
 * to the correct variant values.
 *
 * Usage:
 * ```ts
 * ThemeProvider({ theme: 'dark', children: [myApp] });
 * ```
 */

/** A child node: either a DOM Node or a string (text content). */
export type ThemeChild = Node | string;

/** Props for ThemeProvider. */
export interface ThemeProviderProps {
  /** The theme variant name (e.g., 'light', 'dark'). Defaults to 'light'. */
  theme?: string;
  /** Child elements to render inside the provider. */
  children: ThemeChild[];
}

/**
 * Create a wrapper div with `data-theme` attribute for theme switching.
 *
 * Uses JSX — the runtime handles CSR (DOM elements) and SSR (VNodes)
 * automatically based on which jsx-runtime is loaded.
 */
export function ThemeProvider({ theme = 'light', children }: ThemeProviderProps): HTMLElement {
  return <div data-theme={theme}>{...children}</div>;
}
