/**
 * ThemeProvider — Sets `data-theme` attribute for contextual token switching.
 *
 * Creates a wrapper div element with the appropriate `data-theme` attribute
 * so that contextual CSS custom properties (generated by compileTheme) resolve
 * to the correct variant values.
 *
 * Usage:
 * ```ts
 * ThemeProvider({ theme: 'dark', children: [myApp] });
 * ```
 */
/** A child node: either a DOM Node or a string (text content). */
export type ThemeChild = Node | string;
/** Props for ThemeProvider. */
export interface ThemeProviderProps {
  /** The theme variant name (e.g., 'light', 'dark'). Defaults to 'light'. */
  theme?: string;
  /** Child elements to render inside the provider. */
  children: ThemeChild[];
}
/**
 * Create a wrapper div with `data-theme` attribute for theme switching.
 *
 * @param props - Theme and children.
 * @returns A div element with `data-theme` set and children appended.
 */
export declare function ThemeProvider(props: ThemeProviderProps): HTMLDivElement;
//# sourceMappingURL=theme-provider.d.ts.map
