/**
 * ThemeProvider — Sets `data-theme` attribute for contextual token switching.
 *
 * Creates a wrapper div element with the appropriate `data-theme` attribute
 * so that contextual CSS custom properties (generated by compileTheme) resolve
 * to the correct variant values.
 *
 * Uses __element/__enterChildren/__exitChildren/__append so that during
 * hydration it claims existing SSR nodes instead of creating new elements.
 *
 * Usage:
 * ```ts
 * ThemeProvider({ theme: 'dark', children: [myApp] });
 * ```
 */

import type { ChildValue } from '../component/children';
import { resolveChildren } from '../component/children';
import { __append, __element, __enterChildren, __exitChildren } from '../dom/element';

/** A child node: either a DOM Node or a string (text content). */
export type ThemeChild = Node | string;

/** Props for ThemeProvider. */
export interface ThemeProviderProps {
  /** The theme variant name (e.g., 'light', 'dark'). Defaults to 'light'. */
  theme?: string;
  /** Child elements to render inside the provider. */
  children: ThemeChild[] | (() => ThemeChild | ThemeChild[]);
}

/**
 * Create a wrapper div with `data-theme` attribute for theme switching.
 *
 * Uses __element() directly (instead of jsx()) so the hydration cursor
 * walker can claim the existing SSR node during mount().
 */
export function ThemeProvider({ theme = 'light', children }: ThemeProviderProps): HTMLElement {
  const el = __element('div', { 'data-theme': theme });
  __enterChildren(el);
  const nodes = resolveChildren(children as ChildValue);
  for (const node of nodes) {
    __append(el, node);
  }
  __exitChildren();
  return el;
}
