// @vertz/server — the preferred public API for Vertz HTTP servers.
// Re-exports everything from @vertz/core except the deprecated createApp.

// Re-export all types
export type {
  AccumulateProvides,
  AppBuilder,
  AppConfig,
  BootInstruction,
  BootSequence,
  CorsConfig,
  Ctx,
  DeepReadonly,
  Deps,
  EnvConfig,
  ExtractMethods,
  HandlerCtx,
  HttpMethod,
  HttpStatusCode,
  Infer,
  InferSchema,
  ListenOptions,
  MiddlewareDef,
  Module,
  ModuleBootInstruction,
  ModuleDef,
  NamedMiddlewareDef,
  NamedModule,
  NamedModuleDef,
  NamedRouterDef,
  NamedServiceDef,
  RawRequest,
  ResolveInjectMap,
  RouterDef,
  ServerAdapter,
  ServerHandle,
  ServiceBootInstruction,
  ServiceDef,
  ServiceFactory,
} from '@vertz/core';
export {
  // Exceptions
  BadRequestException,
  ConflictException,
  createEnv,
  // Immutability
  createImmutableProxy,
  createMiddleware,
  createModule,
  createModuleDef,
  createServer,
  deepFreeze,
  ForbiddenException,
  InternalServerErrorException,
  makeImmutable,
  NotFoundException,
  ServiceUnavailableException,
  UnauthorizedException,
  ValidationException,
  VertzException,
  vertz,
} from '@vertz/core';

// Domain API (STUB for TDD red phase)
export { domain } from './domain';
export type {
  DomainDefinition,
  DomainOptions,
  DomainType,
  DomainContext,
  AccessRule,
  AccessRules,
  Result,
  DomainError,
} from './domain';

// Auth Module - Phase 1 & 2
export { 
  createAuth, 
  createAccess, 
  defaultAccess, 
  hashPassword, 
  verifyPassword, 
  validatePassword,
  AuthorizationError,
  // OAuth providers - Phase 2
  google,
  github,
  discord,
  getProviderById,
  validateProviderConfig,
} from './auth';
export type {
  AuthConfig,
  AuthInstance,
  AuthApi,
  AuthResult,
  AuthError,
  AuthUser,
  AuthContext,
  Session,
  SessionPayload,
  SessionStrategy,
  SessionConfig,
  CookieConfig,
  EmailPasswordConfig,
  PasswordRequirements,
  RateLimitConfig,
  RateLimitResult,
  SignUpInput,
  SignInInput,
  AccessConfig,
  AccessInstance,
  Entitlement,
  EntitlementDefinition,
  Resource,
  // OAuth types - Phase 2
  OAuthProvider,
  OAuthConfig,
  OAuthTokens,
  OAuthUserInfo,
  OAuthAuthResult,
  OAuthCallbackResult,
  GoogleOAuthConfig,
  GitHubOAuthConfig,
  DiscordOAuthConfig,
  MFAConfig,
} from './auth';
