// @vertz/server — the preferred public API for Vertz HTTP servers.
// Re-exports everything from @vertz/core except the deprecated createApp.

// Re-export all types
export type {
  AccumulateProvides,
  AppBuilder,
  AppConfig,
  CorsConfig,
  Ctx,
  DeepReadonly,
  Deps,
  EnvConfig,
  HandlerCtx,
  HttpMethod,
  HttpStatusCode,
  Infer,
  InferSchema,
  ListenOptions,
  MiddlewareDef,
  NamedMiddlewareDef,
  RawRequest,
  ServerAdapter,
  ServerHandle,
} from '@vertz/core';
export {
  // Exceptions
  BadRequestException,
  ConflictException,
  createEnv,
  // Immutability
  createImmutableProxy,
  createMiddleware,
  deepFreeze,
  ForbiddenException,
  InternalServerErrorException,
  makeImmutable,
  NotFoundException,
  ServiceUnavailableException,
  UnauthorizedException,
  ValidationException,
  VertzException,
  vertz,
} from '@vertz/core';
export type {
  // Phase 7: Access set types
  AccessCheckData,
  // Phase 6: Resource hierarchy types
  AccessCheckResult,
  AccessConfig,
  AccessContext,
  AccessContextConfig,
  AccessDefinition,
  // Phase 9: Reactive Invalidation types
  AccessEvent,
  AccessEventBroadcaster,
  AccessEventBroadcasterConfig,
  AccessInstance,
  AccessSet,
  AccessWsData,
  AclClaim,
  AddOnRequires,
  AuthApi,
  AuthConfig,
  AuthContext,
  AuthDbClient,
  AuthInstance,
  AuthTokens,
  AuthUser,
  // Phase 5: Billing types
  BillingAdapter,
  BillingEvent,
  BillingEventEmitter,
  BillingEventHandler,
  BillingEventType,
  // Phase 8: Plans & Wallet types
  BillingPeriod,
  ClosureEntry,
  ClosureRow,
  ClosureStore,
  ComputeAccessSetConfig,
  ConsumeResult,
  CookieConfig,
  DbDialectName,
  DefineAccessInput,
  DenialMeta,
  DenialReason,
  EmailPasswordConfig,
  EmailVerificationConfig,
  EmailVerificationStore,
  EncodedAccessSet,
  Entitlement,
  EntitlementDef,
  EntitlementDefinition,
  EntitlementValue,
  EntityDef,
  // Phase 9: Feature Flag types
  FlagStore,
  GrandfatheringState,
  GrandfatheringStore,
  LimitDef,
  LimitOverride,
  LimitOverrideDef,
  MFAStore,
  MfaChallengeData,
  MfaConfig,
  MfaSetupData,
  OAuthAccountStore,
  OAuthProvider,
  OAuthProviderConfig,
  OAuthTokens,
  OAuthUserInfo,
  OrgPlan,
  OverageConfig,
  OverageInput,
  OverrideStore,
  ParentRef,
  PasswordRequirements,
  PasswordResetConfig,
  PasswordResetStore,
  Period,
  PlanDef,
  PlanHashInput,
  PlanPrice,
  PlanSnapshot,
  PlanStore,
  PlanVersionInfo,
  PlanVersionStore,
  PriceInterval,
  RateLimitConfig,
  RateLimitResult,
  RateLimitStore,
  Resource,
  ResourceRef,
  RoleAssignment,
  RoleAssignmentStore,
  RoleAssignmentTableEntry,
  RuleContext,
  Session,
  SessionConfig,
  SessionInfo,
  SessionPayload,
  SessionStore,
  SessionStrategy,
  SignInInput,
  SignUpInput,
  StoredEmailVerification,
  StoredPasswordReset,
  StoredSession,
  StripeBillingAdapterConfig,
  StripeClient,
  StripePrice,
  StripeProduct,
  TenantOverrides,
  UserStore,
  UserTableEntry,
  WalletEntry,
  WalletStore,
  WebhookHandlerConfig,
} from './auth';
// Auth Module
export {
  AUTH_TABLE_NAMES,
  AuthorizationError,
  // DB-backed auth stores
  authModels,
  calculateBillingPeriod,
  checkAddOnCompatibility,
  checkFva,
  computeAccessSet,
  computeEntityAccess,
  // Phase 5: Billing
  computeOverage,
  computePlanHash,
  createAccess,
  createAccessContext,
  createAccessEventBroadcaster,
  createAuth,
  createBillingEventEmitter,
  createPlanManager,
  createStripeBillingAdapter,
  createWebhookHandler,
  DbClosureStore,
  DbFlagStore,
  DbOAuthAccountStore,
  DbPlanStore,
  DbRoleAssignmentStore,
  DbSessionStore,
  DbUserStore,
  decodeAccessSet,
  defaultAccess,
  defineAccess,
  discord,
  encodeAccessSet,
  getIncompatibleAddOns,
  github,
  google,
  hashPassword,
  InMemoryClosureStore,
  InMemoryEmailVerificationStore,
  InMemoryFlagStore,
  InMemoryGrandfatheringStore,
  InMemoryMFAStore,
  InMemoryOAuthAccountStore,
  InMemoryOverrideStore,
  InMemoryPasswordResetStore,
  InMemoryPlanStore,
  InMemoryPlanVersionStore,
  InMemoryRateLimitStore,
  InMemoryRoleAssignmentStore,
  InMemorySessionStore,
  InMemoryUserStore,
  InMemoryWalletStore,
  initializeAuthTables,
  rules,
  validateAuthModels,
  validateOverrides,
  validatePassword,
  verifyPassword,
} from './auth';
// Server — wraps core's createServer with entity route generation
export type { ServerConfig, ServerInstance } from './create-server';
export { createServer } from './create-server';
// Entity API
export type {
  AccessRule,
  BaseContext,
  CrudHandlers,
  CrudResult,
  EntityActionDef,
  EntityConfig,
  EntityContext,
  EntityDbAdapter,
  EntityDefinition,
  EntityErrorResult,
  EntityOperations,
  EntityRelationsConfig,
  EntityRouteOptions,
  ListOptions,
  ListResult,
  RequestInfo,
} from './entity';
export {
  createCrudHandlers,
  createEntityContext,
  EntityRegistry,
  enforceAccess,
  entity,
  entityErrorHandler,
  generateEntityRoutes,
  stripHiddenFields,
  stripReadOnlyFields,
} from './entity';
// Service API
export type { ServiceActionDef, ServiceConfig, ServiceContext, ServiceDefinition } from './service';
export { service } from './service';
