import type { ColumnBuilder, ColumnMetadata, InferColumnType } from './column';
import type { RelationDef } from './relation';
import type { DbExpr } from '../sql/expr';

// ---------------------------------------------------------------------------
// Index Definition
// ---------------------------------------------------------------------------

export type IndexType = 'btree' | 'hash' | 'gin' | 'gist' | 'brin' | 'hnsw';

export interface IndexDef {
  readonly columns: readonly string[];
  readonly name?: string;
  readonly unique?: boolean;
  readonly type?: IndexType;
  readonly where?: string;
}

export interface IndexOptions {
  name?: string;
  unique?: boolean;
  type?: IndexType;
  where?: string;
}

const DANGEROUS_SQL_PATTERN = /;|--|\b(DROP|DELETE|INSERT|UPDATE|ALTER|CREATE|EXEC)\b/i;

export function createIndex(columns: string | string[], options?: IndexOptions): IndexDef {
  if (options?.where && DANGEROUS_SQL_PATTERN.test(options.where)) {
    throw new Error(`Unsafe WHERE clause expression in index: "${options.where}"`);
  }
  return {
    columns: Array.isArray(columns) ? columns : [columns],
    ...options,
  };
}

// ---------------------------------------------------------------------------
// Type-level utilities for deriving types from column definitions
// ---------------------------------------------------------------------------

/** A record of column builders -- the shape passed to d.table(). */
export type ColumnRecord = Record<string, ColumnBuilder<unknown, ColumnMetadata>>;

/** Extract the TypeScript type from every column in a record. */
type InferColumns<T extends ColumnRecord> = {
  [K in keyof T]: InferColumnType<T[K]>;
};

/** Keys of columns where a given metadata property is `true`. */
type ColumnKeysWhere<T extends ColumnRecord, Flag extends keyof ColumnMetadata> = {
  [K in keyof T]: T[K] extends ColumnBuilder<unknown, infer M>
    ? M extends Record<Flag, true>
      ? K
      : never
    : never;
}[keyof T];

/** Keys of columns where a given metadata property is NOT `true` (i.e., false). */
type ColumnKeysWhereNot<T extends ColumnRecord, Flag extends keyof ColumnMetadata> = {
  [K in keyof T]: T[K] extends ColumnBuilder<unknown, infer M>
    ? M extends Record<Flag, true>
      ? never
      : K
    : never;
}[keyof T];

/** True (distributed) if the annotations record contains at least one of the target annotations. */
type HasAnyAnnotation<Ann, A extends string> = A extends keyof Ann
  ? Ann[A] extends true
    ? true
    : never
  : never;

/** Keys of columns that do NOT have ANY of the specified annotations in `_annotations`. */
export type ColumnKeysWithoutAnyAnnotation<T extends ColumnRecord, Annotations extends string> = {
  [K in keyof T]: T[K] extends ColumnBuilder<unknown, infer M>
    ? true extends HasAnyAnnotation<M['_annotations'], Annotations>
      ? never
      : K
    : never;
}[keyof T];

/** Extracts the union of all annotation names present across all columns in a record. */
export type AllAnnotations<T extends ColumnRecord> = {
  [K in keyof T]: T[K] extends ColumnBuilder<unknown, infer M>
    ? keyof M['_annotations'] & string
    : never;
}[keyof T];

// ---------------------------------------------------------------------------
// Derived types
// ---------------------------------------------------------------------------

/**
 * $infer -- default SELECT type.
 * Excludes columns annotated 'hidden'. Includes everything else.
 */
type Infer<T extends ColumnRecord> = {
  [K in ColumnKeysWithoutAnyAnnotation<T, 'hidden'>]: InferColumnType<T[K]>;
};

/**
 * $infer_all -- all columns including hidden.
 */
type InferAll<T extends ColumnRecord> = InferColumns<T>;

/**
 * $insert -- write type. ALL columns included (visibility is read-side only).
 * Columns with hasDefault: true become optional.
 */
type Insert<T extends ColumnRecord> = {
  [K in ColumnKeysWhereNot<T, 'hasDefault'>]: InferColumnType<T[K]>;
} & {
  [K in ColumnKeysWhere<T, 'hasDefault'>]?: InferColumnType<T[K]>;
};

/**
 * $update -- write type. ALL non-primary-key columns, all optional.
 * Primary key excluded (you don't update a PK).
 */
type Update<T extends ColumnRecord> = {
  [K in ColumnKeysWhereNot<T, 'primary'>]?: InferColumnType<T[K]> | DbExpr;
};

/**
 * $response -- API response shape. Excludes columns annotated 'hidden'.
 */
type Response<T extends ColumnRecord> = {
  [K in ColumnKeysWithoutAnyAnnotation<T, 'hidden'>]: InferColumnType<T[K]>;
};

/**
 * Keys of columns where BOTH primary and hasDefault are true.
 * These are auto-generated single-column PKs (e.g., .primary() sets both).
 * Composite PK columns without .default() have primary: true but hasDefault: false.
 */
type AutoGeneratedPKKeys<T extends ColumnRecord> = {
  [K in keyof T]: T[K] extends ColumnBuilder<unknown, infer M>
    ? M extends { primary: true; hasDefault: true }
      ? K
      : never
    : never;
}[keyof T];

/**
 * $create_input -- API create input shape.
 * Excludes readOnly columns and auto-generated PK columns (primary + hasDefault).
 * Composite PK columns without hasDefault are INCLUDED (externally provided).
 * Columns with defaults are optional.
 */
type ApiCreateInput<T extends ColumnRecord> = {
  [K in Exclude<
    ColumnKeysWhereNot<T, 'isReadOnly'> & ColumnKeysWhereNot<T, 'hasDefault'> & string,
    AutoGeneratedPKKeys<T>
  >]: InferColumnType<T[K]>;
} & {
  [K in Exclude<
    ColumnKeysWhereNot<T, 'isReadOnly'> & ColumnKeysWhere<T, 'hasDefault'> & string,
    AutoGeneratedPKKeys<T>
  >]?: InferColumnType<T[K]>;
};

/**
 * $update_input -- API update input shape.
 * Excludes readOnly and primary key columns. All fields optional (partial update).
 */
type ApiUpdateInput<T extends ColumnRecord> = {
  [K in ColumnKeysWhereNot<T, 'isReadOnly'> &
    ColumnKeysWhereNot<T, 'primary'> &
    string]?: InferColumnType<T[K]> | DbExpr;
};

// ---------------------------------------------------------------------------
// TableDef interface
// ---------------------------------------------------------------------------

export interface TableDef<TColumns extends ColumnRecord = ColumnRecord> {
  readonly _name: string;
  readonly _columns: TColumns;
  readonly _indexes: readonly IndexDef[];
  readonly _primaryKey: readonly string[];
  readonly _shared: boolean;
  readonly _tenant: boolean;

  /** Default SELECT type -- excludes columns annotated 'hidden'. */
  readonly $infer: Infer<TColumns>;
  /** All columns including hidden. */
  readonly $infer_all: InferAll<TColumns>;
  /** Insert type -- defaulted columns optional. ALL columns included. */
  readonly $insert: Insert<TColumns>;
  /** Update type -- all non-PK columns optional. ALL columns included. */
  readonly $update: Update<TColumns>;

  /** API response shape — excludes columns annotated 'hidden'. */
  readonly $response: Response<TColumns>;
  /** API create input — excludes readOnly + PK; defaulted columns optional. */
  readonly $create_input: ApiCreateInput<TColumns>;
  /** API update input — excludes readOnly + PK; all fields optional. */
  readonly $update_input: ApiUpdateInput<TColumns>;

  /** Mark this table as shared / cross-tenant. */
  shared(): TableDef<TColumns>;
  /** Mark this table as the tenant root. */
  tenant(): TableDef<TColumns>;
}

// ---------------------------------------------------------------------------
// Table options
// ---------------------------------------------------------------------------

export interface TableOptions {
  relations?: Record<string, RelationDef>;
  indexes?: IndexDef[];
}

export interface TableOptionsWithPK<
  TColumns extends ColumnRecord,
  TPK extends readonly (keyof TColumns & string)[],
> {
  relations?: Record<string, RelationDef>;
  indexes?: IndexDef[];
  primaryKey: TPK;
}

// ---------------------------------------------------------------------------
// MarkAsPrimary — maps composite PK columns to have primary: true in their metadata
// ---------------------------------------------------------------------------

export type MarkAsPrimary<TColumns extends ColumnRecord, TPK extends readonly string[]> = {
  [K in keyof TColumns]: K extends TPK[number]
    ? TColumns[K] extends ColumnBuilder<infer TType, infer TMeta>
      ? ColumnBuilder<TType, Omit<TMeta, 'primary'> & { readonly primary: true }>
      : TColumns[K]
    : TColumns[K];
};

// ---------------------------------------------------------------------------
// createTable factory
// ---------------------------------------------------------------------------

export function createTable<
  TColumns extends ColumnRecord,
  const TPK extends readonly (keyof TColumns & string)[],
>(
  name: string,
  columns: TColumns,
  options: TableOptionsWithPK<TColumns, TPK>,
): TableDef<MarkAsPrimary<TColumns, TPK>>;
export function createTable<TColumns extends ColumnRecord>(
  name: string,
  columns: TColumns,
  options?: TableOptions,
): TableDef<TColumns>;
export function createTable<TColumns extends ColumnRecord>(
  name: string,
  columns: TColumns,
  options?: TableOptions & { primaryKey?: readonly string[] },
): TableDef<TColumns> {
  const pkOption = (options as { primaryKey?: readonly string[] } | undefined)?.primaryKey;
  let finalColumns = columns;

  if (pkOption && pkOption.length === 0) {
    throw new Error(`primaryKey option in table "${name}" must contain at least one column name.`);
  }

  if (pkOption && pkOption.length > 0) {
    // Validate: no column-level .primary() when table-level primaryKey is used
    for (const colName of Object.keys(columns)) {
      if (columns[colName]._meta.primary) {
        throw new Error(
          `Cannot use both column-level .primary() and table-level primaryKey option in table "${name}". ` +
            `Column "${colName}" has .primary(). Remove it or remove the primaryKey option.`,
        );
      }
    }

    // Validate: all primaryKey columns exist
    for (const pkCol of pkOption) {
      if (!(pkCol in columns)) {
        throw new Error(
          `Primary key column "${pkCol}" does not exist in table "${name}". ` +
            `Available columns: ${Object.keys(columns).join(', ')}`,
        );
      }
    }

    // Clone PK columns with primary: true (preserving existing hasDefault)
    const cloned = { ...columns } as Record<string, ColumnBuilder<unknown, ColumnMetadata>>;
    for (const pkCol of pkOption) {
      const col = cloned[pkCol];
      cloned[pkCol] = { ...col, _meta: { ...col._meta, primary: true } };
    }
    finalColumns = cloned as TColumns;
  }

  return createTableInternal(name, finalColumns, options?.indexes ?? [], false, false, pkOption);
}

function derivePrimaryKey<TColumns extends ColumnRecord>(
  columns: TColumns,
  explicit?: readonly string[],
): readonly string[] {
  if (explicit) return explicit;
  // Derive from column-level .primary()
  const pk: string[] = [];
  for (const [colName, col] of Object.entries(columns)) {
    if (col._meta.primary) pk.push(colName);
  }
  return pk;
}

function createTableInternal<TColumns extends ColumnRecord>(
  name: string,
  columns: TColumns,
  indexes: readonly IndexDef[],
  shared: boolean,
  isTenant: boolean,
  explicitPk?: readonly string[],
): TableDef<TColumns> {
  const primaryKey = derivePrimaryKey(columns, explicitPk);
  const table: TableDef<TColumns> = {
    _name: name,
    _columns: columns,
    _indexes: indexes,
    _primaryKey: primaryKey,
    _shared: shared,
    _tenant: isTenant,

    // Derived type properties are phantom -- they exist only at the type level.
    // At runtime they are never accessed; we use `undefined as never` to avoid
    // allocating objects that would never be read.
    get $infer(): Infer<TColumns> {
      return undefined as never;
    },
    get $infer_all(): InferAll<TColumns> {
      return undefined as never;
    },
    get $insert(): Insert<TColumns> {
      return undefined as never;
    },
    get $update(): Update<TColumns> {
      return undefined as never;
    },
    get $response(): Response<TColumns> {
      return undefined as never;
    },
    get $create_input(): ApiCreateInput<TColumns> {
      return undefined as never;
    },
    get $update_input(): ApiUpdateInput<TColumns> {
      return undefined as never;
    },

    shared() {
      if (isTenant) {
        throw new Error(
          `Table "${name}" is already marked as .tenant(). A table cannot be both .tenant() and .shared().`,
        );
      }
      return createTableInternal(name, columns, indexes, true, false, explicitPk);
    },

    tenant() {
      if (shared) {
        throw new Error(
          `Table "${name}" is already marked as .shared(). A table cannot be both .shared() and .tenant().`,
        );
      }
      return createTableInternal(name, columns, indexes, false, true, explicitPk);
    },
  };
  return table;
}
