import { jsonSchemaToTS } from '../../json-schema-converter';
import type { CodegenIR, CodegenOperation, GeneratedFile } from '../../types';

const FILE_HEADER = '// Generated by @vertz/codegen — do not edit\n';

function paramsToTS(op: CodegenOperation): string {
  if (!op.params) {
    return 'Record<string, never>';
  }
  const ref = op.schemaRefs.params;
  if (ref) {
    return ref;
  }
  const result = jsonSchemaToTS(op.params);
  return result.type;
}

function queryToTS(op: CodegenOperation): string {
  if (!op.query) {
    return 'Record<string, never>';
  }
  const ref = op.schemaRefs.query;
  if (ref) {
    return ref;
  }
  const result = jsonSchemaToTS(op.query);
  return result.type;
}

function bodyToTS(op: CodegenOperation): string {
  if (!op.body) {
    return 'never';
  }
  const ref = op.schemaRefs.body;
  if (ref) {
    return ref;
  }
  const result = jsonSchemaToTS(op.body);
  return result.type;
}

function headersToTS(op: CodegenOperation): string {
  if (!op.headers) {
    return 'Record<string, never>';
  }
  const ref = op.schemaRefs.headers;
  if (ref) {
    return ref;
  }
  const result = jsonSchemaToTS(op.headers);
  return result.type;
}

function responseToTS(op: CodegenOperation): string {
  if (!op.response) {
    return 'void';
  }
  const ref = op.schemaRefs.response;
  if (ref) {
    return ref;
  }
  const result = jsonSchemaToTS(op.response);
  return result.type;
}

function emitRouteEntry(op: CodegenOperation): string {
  const routeKey = `${op.method} ${op.path}`;
  const params = paramsToTS(op);
  const query = queryToTS(op);
  const body = bodyToTS(op);
  const headers = headersToTS(op);
  const response = responseToTS(op);

  return `  '${routeKey}': { params: ${params}; query: ${query}; body: ${body}; headers: ${headers}; response: ${response} };`;
}

/**
 * Emits a route map interface that maps route keys (e.g., 'GET /users/:id')
 * to their input/output types for type-safe test app usage.
 */
export function emitRouteMapType(ir: CodegenIR): GeneratedFile {
  const sections: string[] = [FILE_HEADER];

  sections.push('export interface AppRouteMap {');

  // Collect all operations from all modules
  const operations = ir.modules.flatMap((mod) => mod.operations);

  if (operations.length === 0) {
    sections.push('  [key: string]: never;');
  } else {
    const entries = operations.map((op) => emitRouteEntry(op));
    sections.push(entries.join('\n'));
  }

  sections.push('}');

  return {
    path: 'types/routes.ts',
    content: sections.join('\n'),
  };
}
