/**
 * WranglerConfigGenerator — generates wrangler.toml for Cloudflare Workers deployment
 *
 * Reads the deployment manifest and generates a wrangler.toml with:
 * - Worker name and entry point
 * - Compatibility date and flags (nodejs_compat_v2)
 * - D1 database bindings
 * - Static assets configuration (if full-stack)
 */

import type { DeploymentManifest } from './types';

export class WranglerConfigGenerator {
  constructor(
    private readonly manifest: DeploymentManifest,
    private readonly workerName: string,
  ) {}

  generate(): string {
    const sections: string[] = [];

    sections.push(this.generateHeader());
    sections.push(this.generateD1Bindings());

    if (this.manifest.assets.hasClient) {
      sections.push(this.generateAssets());
    }

    return sections.filter(Boolean).join('\n');
  }

  private generateHeader(): string {
    const lines: string[] = [
      '# Generated by Vertz — do not edit manually.',
      '# Customize deployment via vertz deploy --config <your-config.toml>',
      '',
      `name = "${this.workerName}"`,
      'main = "index.js"',
      `compatibility_date = "${this.getCompatibilityDate()}"`,
      'compatibility_flags = ["nodejs_compat_v2"]',
      '',
    ];
    return lines.join('\n');
  }

  private generateD1Bindings(): string {
    const d1Bindings = this.manifest.bindings.filter((b) => b.type === 'd1');
    if (d1Bindings.length === 0) return '';

    const lines: string[] = [];
    for (const binding of d1Bindings) {
      lines.push('[[d1_databases]]');
      lines.push(`binding = "${binding.name}"`);
      lines.push(`database_name = "${this.workerName}-db"`);
      lines.push(
        `database_id = "local"  # Replace with actual D1 database ID after running: wrangler d1 create ${this.workerName}-db`,
      );
      lines.push('');
    }
    return lines.join('\n');
  }

  private generateAssets(): string {
    const dir = this.manifest.assets.clientDir ?? 'dist/client';
    const lines: string[] = ['[assets]', `directory = "${dir}"`, ''];
    return lines.join('\n');
  }

  private getCompatibilityDate(): string {
    // Use a stable date — not today's date, to ensure reproducible builds
    return '2026-03-01';
  }
}
