import type { FetchError, Result } from '@vertz/errors';
import { ok } from '@vertz/errors';
import type {
  EntityQueryMeta,
  FetchResponse,
  MutationMeta,
  OptimisticHandler,
  QueryParams,
} from './types';

export interface QueryDescriptor<T, E = FetchError> extends PromiseLike<Result<T, E>> {
  readonly _tag: 'QueryDescriptor';
  readonly _key: string;
  readonly _fetch: () => Promise<Result<T, E>>;
  /** Entity metadata for entity-backed queries. */
  readonly _entity?: EntityQueryMeta;
  /** Phantom field to carry the error type through generics. Never set at runtime. */
  readonly _error?: E;
}

/**
 * Descriptor for a streaming endpoint.  Mirrors QueryDescriptor for snapshot
 * endpoints — carries a derived cache key plus a factory that, given an
 * AbortSignal, opens the underlying AsyncIterable.
 *
 * Generated by `@vertz/openapi` for streaming operations and consumed by
 * `query()` from `@vertz/ui`.  The `_key` is built with the same scheme as
 * QueryDescriptor so REST and stream descriptors produce identical keys
 * for identical method/path/args.
 */
export interface StreamDescriptor<T> {
  readonly _tag: 'StreamDescriptor';
  readonly _key: string;
  readonly _stream: (signal: AbortSignal) => AsyncIterable<T>;
  /** Phantom field to carry the payload type through generics. Never set at runtime. */
  readonly _payload?: T;
}

export interface MutationDescriptor<T, E = FetchError> extends PromiseLike<Result<T, E>> {
  readonly _tag: 'MutationDescriptor';
  readonly _key: string;
  readonly _fetch: () => Promise<Result<T, E>>;
  readonly _mutation: MutationMeta;
  /** Phantom field to carry the error type through generics. Never set at runtime. */
  readonly _error?: E;
}

export function isQueryDescriptor<T, E = FetchError>(
  value: unknown,
): value is QueryDescriptor<T, E> {
  return (
    value !== null &&
    typeof value === 'object' &&
    '_tag' in value &&
    (value as Record<string, unknown>)._tag === 'QueryDescriptor'
  );
}

export function createDescriptor<T>(
  method: string,
  path: string,
  fetchFn: () => Promise<FetchResponse<T>>,
  query?: QueryParams,
  entity?: EntityQueryMeta,
): QueryDescriptor<T> {
  const key = `${method}:${path}${serializeQueryParams(query)}`;

  const fetchResult = async (): Promise<Result<T, FetchError>> => {
    const response = await fetchFn();
    if (!response.ok) return response;
    return ok(response.data.data);
  };

  return {
    _tag: 'QueryDescriptor' as const,
    _key: key,
    _fetch: fetchResult,
    ...(entity ? { _entity: entity } : {}),

    then(onFulfilled, onRejected) {
      return fetchResult().then(onFulfilled, onRejected);
    },
  };
}

/**
 * Type guard.  Checks the discriminant tag *and* `_stream` callability so
 * a hand-rolled `{ _tag: 'StreamDescriptor' }` without a function doesn't
 * pass (defense against malformed inputs from non-codegen sources).
 */
export function isStreamDescriptor<T>(value: unknown): value is StreamDescriptor<T> {
  if (value === null || typeof value !== 'object') return false;
  const v = value as Record<string, unknown>;
  return v._tag === 'StreamDescriptor' && typeof v._stream === 'function';
}

/**
 * Build a StreamDescriptor with a derived key in the same shape
 * QueryDescriptor uses (`METHOD:path?args` — see createDescriptor for the
 * canonical scheme).  Used by codegen and hand-written stream wrappers.
 */
export function createStreamDescriptor<T>(
  method: string,
  path: string,
  streamFn: (signal: AbortSignal) => AsyncIterable<T>,
  query?: QueryParams,
): StreamDescriptor<T> {
  return {
    _tag: 'StreamDescriptor' as const,
    _key: `${method}:${path}${serializeQueryParams(query)}`,
    _stream: streamFn,
  };
}

export function isMutationDescriptor<T, E = FetchError>(
  value: unknown,
): value is MutationDescriptor<T, E> {
  return (
    value !== null &&
    typeof value === 'object' &&
    '_tag' in value &&
    (value as Record<string, unknown>)._tag === 'MutationDescriptor'
  );
}

export function createMutationDescriptor<T>(
  method: string,
  path: string,
  fetchFn: () => Promise<FetchResponse<T>>,
  mutation: MutationMeta,
  handler?: OptimisticHandler,
): MutationDescriptor<T> {
  const key = `${method}:${path}`;
  let mutationCounter = 0;

  const fetchResult = async (): Promise<Result<T, FetchError>> => {
    const response = await fetchFn();
    if (!response.ok) return response;
    return ok(response.data.data);
  };

  return {
    _tag: 'MutationDescriptor' as const,
    _key: key,
    _mutation: mutation,
    _fetch: fetchResult,

    then(onFulfilled, onRejected) {
      const id = `m_${++mutationCounter}_${Date.now().toString(36)}`;

      // 1. Apply optimistic update (synchronous)
      const rollback = handler?.apply(mutation, id);

      // 2. Execute fetch
      return fetchResult().then(
        (result) => {
          if (result.ok) {
            handler?.commit(mutation, id, result.data);
          } else {
            rollback?.();
          }
          return onFulfilled?.(result) ?? (result as never);
        },
        (err) => {
          rollback?.();
          if (onRejected) return onRejected(err);
          throw err;
        },
      );
    },
  };
}

/**
 * Serialize query params into a deterministic, URL-encoded string suitable
 * for use as part of a cache key.  Keys are sorted alphabetically; null and
 * undefined values are dropped.  Returns `''` (empty) when there are no
 * effective params, otherwise the result is prefixed with `?`.
 *
 * Exported so `createStreamDescriptor` can derive its `_key` using the same
 * scheme as `createDescriptor` — REST and stream descriptors must produce
 * identical keys for identical method/path/args.
 */
export function serializeQueryParams(query?: QueryParams): string {
  if (!query) return '';
  const params = new URLSearchParams();
  for (const [key, value] of Object.entries(query).sort(([a], [b]) => a.localeCompare(b))) {
    if (value !== undefined && value !== null) {
      params.set(key, String(value));
    }
  }
  const str = params.toString();
  return str ? `?${str}` : '';
}
