import type { CodegenAccess, CodegenIR, GeneratedFile, Generator, GeneratorConfig } from '../types';

const FILE_HEADER = '// Generated by @vertz/codegen — do not edit\n\n';

export class AccessTypesGenerator implements Generator {
  readonly name = 'access-types';

  generate(ir: CodegenIR, _config: GeneratorConfig): GeneratedFile[] {
    if (!ir.access || ir.access.entitlements.length === 0) {
      return [];
    }

    return [
      {
        path: 'access.d.ts',
        content: renderAccessTypes(ir.access),
      },
    ];
  }
}

function escapeStringLiteral(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function renderAccessTypes(access: CodegenAccess): string {
  const lines: string[] = [FILE_HEADER];

  // Registry entries for entitlements
  const registryEntries = access.entitlements
    .map((e) => `    '${escapeStringLiteral(e)}': true;`)
    .join('\n');

  // Module augmentation: @vertz/server — populate EntitlementRegistry
  lines.push("declare module '@vertz/server' {");
  lines.push('  interface EntitlementRegistry {');
  lines.push(registryEntries);
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // Module augmentation: @vertz/ui/auth — populate EntitlementRegistry
  lines.push("declare module '@vertz/ui/auth' {");
  lines.push('  interface EntitlementRegistry {');
  lines.push(registryEntries);
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // ResourceType and Role<T> — only if entities with roles exist
  const entitiesWithRoles = access.entities.filter((e) => e.roles.length > 0);
  if (entitiesWithRoles.length > 0) {
    const resourceUnion = entitiesWithRoles
      .map((e) => `'${escapeStringLiteral(e.name)}'`)
      .join(' | ');
    lines.push(`type ResourceType = ${resourceUnion};`);
    lines.push('');

    // Role<T> conditional type
    lines.push('type Role<T extends ResourceType> =');
    entitiesWithRoles.forEach((entity, i) => {
      const rolesUnion = entity.roles.map((r) => `'${escapeStringLiteral(r)}'`).join(' | ');
      const prefix = i === 0 ? '  ' : '  : ';
      lines.push(`${prefix}T extends '${escapeStringLiteral(entity.name)}' ? ${rolesUnion}`);
    });
    lines.push('  : never;');
    lines.push('');
  }

  return lines.join('\n');
}
