import type {
  CodegenAuthOperation,
  CodegenIR,
  GeneratedFile,
  Generator,
  GeneratorConfig,
} from '../types';

const FILE_HEADER = '// Generated by @vertz/codegen — do not edit\n\n';

export class AuthSdkGenerator implements Generator {
  readonly name = 'auth-sdk';

  generate(ir: CodegenIR, _config: GeneratorConfig): GeneratedFile[] {
    if (!ir.auth.operations.length) return [];

    return [this.generateAuthSdk(ir.auth.operations)];
  }

  private generateAuthSdk(operations: CodegenAuthOperation[]): GeneratedFile {
    const lines: string[] = [FILE_HEADER];

    // --- Types ---
    lines.push(this.generateTypes(operations));

    // --- Cookie jar ---
    lines.push(this.generateCookieJar());

    // --- Auth fetch helper ---
    lines.push(this.generateAuthFetch());

    // --- createAuthSdk factory ---
    lines.push(this.generateFactory(operations));

    return { path: 'auth.ts', content: lines.join('\n') };
  }

  private generateTypes(operations: CodegenAuthOperation[]): string {
    const lines: string[] = [];
    const hasOp = (id: string) => operations.some((op) => op.operationId === id);

    lines.push(`import type { Result } from '@vertz/fetch';`);
    lines.push('');

    // AuthCookie
    lines.push(`export interface AuthCookie {
  name: string;
  value: string;
  domain: string;
  path: string;
  httpOnly?: boolean;
  secure?: boolean;
  sameSite?: 'Strict' | 'Lax' | 'None';
  expires?: number;
}`);
    lines.push('');

    // AuthError
    lines.push(`export type AuthErrorCode =
  | 'INVALID_CREDENTIALS'
  | 'USER_EXISTS'
  | 'MFA_REQUIRED'
  | 'RATE_LIMITED'
  | 'NETWORK_ERROR'
  | 'UNKNOWN_ERROR';

export interface AuthError extends Error {
  code: AuthErrorCode;
  statusCode: number;
  retryAfter?: number;
}`);
    lines.push('');

    // AuthUser
    lines.push(`export interface AuthUser {
  id: string;
  email: string;
  role: string;
  [key: string]: unknown;
}`);
    lines.push('');

    // AuthResponse
    lines.push(`export interface AuthResponse {
  user: AuthUser;
  expiresAt: number;
}`);
    lines.push('');

    // AuthSession
    lines.push(`export interface AuthSession {
  user: AuthUser;
  expiresAt: number;
  tenantId?: string;
}`);
    lines.push('');

    // Input types — only for operations that exist
    if (hasOp('signIn')) {
      lines.push(`export interface SignInInput {
  email: string;
  password: string;
}`);
      lines.push('');
    }

    if (hasOp('signUp')) {
      lines.push(`export interface SignUpInput {
  email: string;
  password: string;
  [key: string]: unknown;
}`);
      lines.push('');
    }

    if (hasOp('switchTenant')) {
      lines.push(`export interface SwitchTenantInput {
  tenantId: string;
}`);
      lines.push('');

      lines.push(`export interface SwitchTenantResponse {
  tenantId: string;
  user: AuthUser;
  expiresAt: number;
}`);
      lines.push('');
    }

    if (hasOp('listTenants')) {
      lines.push(`export interface TenantInfo {
  id: string;
  name: string;
  [key: string]: unknown;
}`);
      lines.push('');

      lines.push(`export interface ListTenantsResponse {
  tenants: TenantInfo[];
  currentTenantId?: string;
  lastTenantId?: string;
  resolvedDefaultId?: string;
}`);
      lines.push('');
    }

    // SdkMethodWithMeta type (inline — avoids extra import dependency)
    lines.push(`type SdkMethodWithMeta<TBody, TResult> = ((body: TBody) => Promise<Result<TResult, AuthError>>) & {
  url: string;
  method: string;
  meta: { bodySchema?: { parse(data: unknown): { ok: boolean; data?: TBody; error?: Error } } };
};`);
    lines.push('');

    // AuthSdk interface — only includes operations that exist
    lines.push('export interface AuthSdk {');

    if (hasOp('signIn')) {
      lines.push('  signIn: SdkMethodWithMeta<SignInInput, AuthResponse>;');
    }
    if (hasOp('signUp')) {
      lines.push('  signUp: SdkMethodWithMeta<SignUpInput, AuthResponse>;');
    }
    if (hasOp('switchTenant')) {
      lines.push('  switchTenant: SdkMethodWithMeta<SwitchTenantInput, SwitchTenantResponse>;');
    }
    if (hasOp('signOut')) {
      lines.push('  signOut: () => Promise<Result<{ ok: true }, AuthError>>;');
    }
    if (hasOp('session')) {
      lines.push('  session: () => Promise<Result<{ session: AuthSession | null }, AuthError>>;');
    }
    if (hasOp('refresh')) {
      lines.push('  refresh: () => Promise<Result<AuthResponse, AuthError>>;');
    }
    if (hasOp('listTenants')) {
      lines.push('  listTenants: () => Promise<Result<ListTenantsResponse, AuthError>>;');
    }
    if (hasOp('providers')) {
      lines.push(
        '  providers: () => Promise<Result<{ id: string; name: string; authUrl: string }[], AuthError>>;',
      );
    }

    lines.push(
      '  /** Accumulated cookies. Populated in Node.js/Bun; empty in browser (warns in dev). */',
    );
    lines.push('  cookies: () => AuthCookie[];');
    lines.push('}');
    lines.push('');

    return lines.join('\n');
  }

  private generateCookieJar(): string {
    return `// --- Cookie Jar (test-grade, for Node.js/Bun E2E test setup) ---

const IS_BROWSER = typeof window !== 'undefined' && typeof document !== 'undefined';

function parseSetCookies(response: Response, requestUrl: string): AuthCookie[] {
  if (IS_BROWSER) return [];

  const setCookies = (response.headers as any).getSetCookie?.() as string[] | undefined;
  if (!setCookies) return [];

  const url = new URL(requestUrl);
  return setCookies.map((header) => {
    const parts = header.split(';').map((s) => s.trim());
    const [nameValue, ...attrs] = parts;
    const eqIdx = nameValue.indexOf('=');
    const name = nameValue.slice(0, eqIdx);
    const value = nameValue.slice(eqIdx + 1);

    const cookie: AuthCookie = {
      name,
      value,
      domain: url.hostname,
      path: '/',
    };

    for (const attr of attrs) {
      const lower = attr.toLowerCase();
      if (lower.startsWith('path=')) {
        cookie.path = attr.slice(5);
      } else if (lower.startsWith('domain=')) {
        cookie.domain = attr.slice(7);
      } else if (lower === 'httponly') {
        cookie.httpOnly = true;
      } else if (lower === 'secure') {
        cookie.secure = true;
      } else if (lower.startsWith('samesite=')) {
        const val = attr.slice(9);
        if (val === 'Strict' || val === 'Lax' || val === 'None') {
          cookie.sameSite = val;
        }
      } else if (lower.startsWith('max-age=')) {
        const maxAge = parseInt(attr.slice(8), 10);
        if (!isNaN(maxAge)) {
          cookie.expires = Math.floor(Date.now() / 1000) + maxAge;
        }
      }
    }

    return cookie;
  });
}

interface CookieJar {
  update(response: Response, requestUrl: string): void;
  headerFor(requestUrl: string): string;
  getAll(): AuthCookie[];
}

function createCookieJar(): CookieJar {
  const cookies: AuthCookie[] = [];

  return {
    update(response: Response, requestUrl: string) {
      const parsed = parseSetCookies(response, requestUrl);
      for (const incoming of parsed) {
        // Replace existing cookie with same name+path
        const idx = cookies.findIndex(
          (c) => c.name === incoming.name && c.path === incoming.path,
        );
        if (idx >= 0) {
          cookies[idx] = incoming;
        } else {
          cookies.push(incoming);
        }
      }
    },

    headerFor(requestUrl: string): string {
      const url = new URL(requestUrl);
      const now = Math.floor(Date.now() / 1000);
      return cookies
        .filter((c) => {
          // Exclude expired cookies
          if (c.expires && c.expires < now) return false;
          // Path matching: cookie path must be a prefix of request path
          return url.pathname.startsWith(c.path);
        })
        .map((c) => \`\${c.name}=\${c.value}\`)
        .join('; ');
    },

    getAll(): AuthCookie[] {
      const now = Math.floor(Date.now() / 1000);
      return cookies.filter((c) => !c.expires || c.expires >= now);
    },
  };
}
`;
  }

  private generateAuthFetch(): string {
    return `// --- Auth Fetch Helper ---

function parseAuthErrorCode(status: number): AuthErrorCode {
  switch (status) {
    case 401: return 'INVALID_CREDENTIALS';
    case 409: return 'USER_EXISTS';
    case 403: return 'MFA_REQUIRED';
    case 429: return 'RATE_LIMITED';
    default: return 'UNKNOWN_ERROR';
  }
}

async function authFetch<T>(
  url: string,
  method: 'GET' | 'POST',
  jar: CookieJar,
  body?: unknown,
): Promise<Result<T, AuthError>> {
  const headers: Record<string, string> = {
    'X-VTZ-Request': '1',
  };

  if (body) {
    headers['Content-Type'] = 'application/json';
  }

  // In Node.js, send accumulated cookies
  if (!IS_BROWSER) {
    const cookieHeader = jar.headerFor(url);
    if (cookieHeader) {
      headers['Cookie'] = cookieHeader;
    }
  }

  try {
    const res = await fetch(url, {
      method,
      headers,
      body: body ? JSON.stringify(body) : undefined,
      credentials: IS_BROWSER ? 'include' : undefined,
    });

    // Update cookie jar from response
    jar.update(res, url);

    if (!res.ok) {
      let message = \`Auth \${method} \${url} failed (\${res.status})\`;
      let retryAfter: number | undefined;

      try {
        const errBody = await res.json();
        if (errBody.message) message = errBody.message;
      } catch {}

      if (res.status === 429) {
        const ra = res.headers.get('Retry-After');
        if (ra) retryAfter = parseInt(ra, 10);
      }

      const error = Object.assign(new Error(message), {
        code: parseAuthErrorCode(res.status),
        statusCode: res.status,
        retryAfter,
      }) as AuthError;

      return { ok: false, error };
    }

    const data = (await res.json()) as T;
    return { ok: true, data };
  } catch (err) {
    const error = Object.assign(new Error((err as Error).message ?? 'Network error'), {
      code: 'NETWORK_ERROR' as const,
      statusCode: 0,
    }) as AuthError;
    return { ok: false, error };
  }
}
`;
  }

  private generateFactory(operations: CodegenAuthOperation[]): string {
    const lines: string[] = [];

    lines.push(`export function createAuthSdk(options: { basePath: string }): AuthSdk {`);
    lines.push('  const { basePath } = options;');
    lines.push('  const jar = createCookieJar();');
    lines.push('');

    // Generate form-compatible methods (SdkMethodWithMeta)
    for (const op of operations.filter((o) => o.hasBody)) {
      const inputType = this.getInputType(op.operationId);
      const outputType = this.getOutputType(op.operationId);
      if (!inputType || !outputType) continue;

      lines.push(`  const ${op.operationId} = Object.assign(`);
      lines.push(`    (body: ${inputType}): Promise<Result<${outputType}, AuthError>> =>`);
      lines.push(
        `      authFetch<${outputType}>(\`\${basePath}${op.path}\`, '${op.method}', jar, body),`,
      );
      lines.push('    {');
      lines.push(`      url: \`\${basePath}${op.path}\`,`);
      lines.push(`      method: '${op.method}' as const,`);
      lines.push('      meta: {},');
      lines.push(`    },`);
      lines.push(`  ) as SdkMethodWithMeta<${inputType}, ${outputType}>;`);
      lines.push('');
    }

    // Build return object
    lines.push('  return {');

    for (const op of operations) {
      if (op.hasBody) {
        lines.push(`    ${op.operationId},`);
      } else {
        const outputType = this.getOutputType(op.operationId);
        if (outputType) {
          lines.push(
            `    ${op.operationId}: () => authFetch<${outputType}>(\`\${basePath}${op.path}\`, '${op.method}', jar),`,
          );
        }
      }
    }

    // cookies() method
    lines.push('    cookies() {');
    lines.push('      if (IS_BROWSER) {');
    lines.push(
      "        console.warn('[vertz] cookies() is only available in Node.js/Bun. In the browser, cookies are managed automatically.');",
    );
    lines.push('        return [];');
    lines.push('      }');
    lines.push('      return jar.getAll();');
    lines.push('    },');

    lines.push('  };');
    lines.push('}');

    return lines.join('\n');
  }

  private getInputType(operationId: string): string | undefined {
    switch (operationId) {
      case 'signIn':
        return 'SignInInput';
      case 'signUp':
        return 'SignUpInput';
      case 'switchTenant':
        return 'SwitchTenantInput';
      default:
        return undefined;
    }
  }

  private getOutputType(operationId: string): string | undefined {
    switch (operationId) {
      case 'signIn':
      case 'signUp':
      case 'refresh':
        return 'AuthResponse';
      case 'signOut':
        return '{ ok: true }';
      case 'switchTenant':
        return 'SwitchTenantResponse';
      case 'session':
        return '{ session: AuthSession | null }';
      case 'listTenants':
        return 'ListTenantsResponse';
      case 'providers':
        return '{ id: string; name: string; authUrl: string }[]';
      default:
        return undefined;
    }
  }
}
