import { posix } from 'node:path';
import type {
  CodegenAuthScheme,
  CodegenEntityModule,
  CodegenIR,
  GeneratedFile,
  Generator,
  GeneratorConfig,
} from '../types';
import { toCamelCase, toPascalCase } from '../utils/naming';
import { generateRelationManifest } from './relation-manifest-generator';

function authFieldName(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

function generateAuthField(scheme: CodegenAuthScheme): string {
  switch (scheme.type) {
    case 'bearer':
      return `  ${authFieldName(scheme.name)}?: string | (() => string | Promise<string>);`;
    case 'basic':
      return `  ${authFieldName(scheme.name)}?: { username: string; password: string };`;
    case 'apiKey':
      return `  ${authFieldName(scheme.name)}?: string | (() => string | Promise<string>);`;
    case 'oauth2':
      return `  ${authFieldName(scheme.name)}?: string | (() => string | Promise<string>);`;
  }
}

function generateAuthStrategy(scheme: CodegenAuthScheme): string[] {
  const fieldName = authFieldName(scheme.name);
  const lines: string[] = [];

  switch (scheme.type) {
    case 'bearer':
      lines.push(
        `      ...(options.auth?.${fieldName} ? [{ type: 'bearer' as const, token: options.auth?.${fieldName} }] : []),`,
      );
      break;
    case 'basic':
      lines.push(
        `      ...(options.auth?.${fieldName} ? [{ type: 'basic' as const, ...options.auth?.${fieldName} }] : []),`,
      );
      break;
    case 'apiKey':
      lines.push(
        `      ...(options.auth?.${fieldName} ? [{ type: 'apiKey' as const, key: options.auth?.${fieldName}, location: '${scheme.in}' as const, name: '${scheme.paramName}' }] : []),`,
      );
      break;
    case 'oauth2':
      lines.push(
        `      ...(options.auth?.${fieldName} ? [{ type: 'bearer' as const, token: options.auth?.${fieldName} }] : []),`,
      );
      break;
  }

  return lines;
}

const FILE_HEADER = '// Generated by @vertz/codegen — do not edit\n\n';

export class ClientGenerator implements Generator {
  readonly name = 'client';

  generate(ir: CodegenIR, config: GeneratorConfig): GeneratedFile[] {
    return [
      this.generateClient(ir),
      this.generatePackageJson(config.outputDir),
      this.generateReadme(ir),
    ];
  }

  private generateClient(ir: CodegenIR): GeneratedFile {
    const entities = ir.entities ?? [];
    const services = (ir.services ?? []).filter((s) => s.actions.length > 0);
    const hasAuth = ir.auth.operations.length > 0;
    const authSchemes = ir.auth.schemes ?? [];
    const hasAuthSchemes = authSchemes.length > 0;
    const hasMutations = entities.some((e) =>
      e.operations.some(
        (op) => op.kind === 'create' || op.kind === 'update' || op.kind === 'delete',
      ),
    );
    const manifest = generateRelationManifest(entities);
    const hasRelations = manifest.some((entry) => Object.keys(entry.schema).length > 0);
    const lines: string[] = [FILE_HEADER];

    if (entities.length > 0 || services.length > 0) {
      if (hasMutations) {
        lines.push("import { FetchClient, type OptimisticHandler } from '@vertz/fetch';");
        if (hasRelations) {
          lines.push(
            "import { createOptimisticHandler, getEntityStore, registerRelationSchema } from '@vertz/ui';",
          );
        } else {
          lines.push("import { createOptimisticHandler, getEntityStore } from '@vertz/ui';");
        }
      } else {
        lines.push("import { FetchClient } from '@vertz/fetch';");
        if (hasRelations) {
          lines.push("import { registerRelationSchema } from '@vertz/ui';");
        }
      }

      for (const entity of entities) {
        const pascal = toPascalCase(entity.entityName);
        lines.push(`import { create${pascal}Sdk } from './entities/${entity.entityName}';`);
      }

      for (const svc of services) {
        const pascal = toPascalCase(svc.serviceName);
        lines.push(`import { create${pascal}Sdk } from './services/${svc.serviceName}';`);
      }
    }

    if (hasAuth) {
      lines.push("import { createAuthSdk } from './auth';");
    }

    if (entities.length > 0 || services.length > 0 || hasAuth) {
      lines.push('');
    }

    if (entities.length > 0) {
      // Emit registerRelationSchema calls
      if (hasRelations) {
        for (const entry of manifest) {
          const schemaEntries = Object.entries(entry.schema);
          if (schemaEntries.length === 0) {
            lines.push(`registerRelationSchema('${entry.entityType}', {});`);
          } else {
            lines.push(`registerRelationSchema('${entry.entityType}', {`);
            for (const [field, def] of schemaEntries) {
              lines.push(`  ${field}: { type: '${def.type}', entity: '${def.entity}' },`);
            }
            lines.push('});');
          }
        }
        lines.push('');
      }
    }

    if (hasAuthSchemes) {
      lines.push('export interface ClientAuth {');
      for (const scheme of authSchemes) {
        lines.push(generateAuthField(scheme));
      }
      lines.push('}');
      lines.push('');
    }

    lines.push('export interface ClientOptions {');
    lines.push('  baseURL?: string;');
    lines.push('  headers?: Record<string, string>;');
    lines.push('  timeoutMs?: number;');
    if (hasMutations) {
      lines.push('  optimistic?: OptimisticHandler | false;');
    }
    if (hasAuthSchemes) {
      lines.push('  auth?: ClientAuth;');
    }
    lines.push('}');
    lines.push('');

    lines.push('export function createClient(options: ClientOptions = {}) {');

    if (entities.length > 0 || services.length > 0 || hasAuth) {
      const baseURLDefault = "options.baseURL ?? '/api'";

      if (entities.length > 0 || services.length > 0) {
        if (hasAuthSchemes) {
          lines.push(`  const client = new FetchClient({`);
          lines.push(`    baseURL: ${baseURLDefault},`);
          lines.push('    headers: options.headers,');
          lines.push('    timeoutMs: options.timeoutMs,');
          lines.push("    credentials: 'include',");
          lines.push('    authStrategies: [');
          for (const scheme of authSchemes) {
            lines.push(...generateAuthStrategy(scheme));
          }
          lines.push('    ],');
          lines.push('  });');
        } else {
          lines.push(
            `  const client = new FetchClient({ baseURL: ${baseURLDefault}, headers: options.headers, timeoutMs: options.timeoutMs, credentials: 'include' });`,
          );
        }
        if (hasMutations) {
          lines.push(
            '  const optimistic = options.optimistic !== false ? (options.optimistic ?? createOptimisticHandler(getEntityStore())) : undefined;',
          );
        }
      }

      if (hasAuth) {
        const authBasePath = `\`\${${baseURLDefault}}/auth\``;
        lines.push(`  const auth = createAuthSdk({ basePath: ${authBasePath} });`);
      }

      lines.push('  return {');
      for (const entity of entities) {
        const pascal = toPascalCase(entity.entityName);
        const camel = toCamelCase(entity.entityName);
        const entityHasMutations = entity.operations.some(
          (op) => op.kind === 'create' || op.kind === 'update' || op.kind === 'delete',
        );
        if (entityHasMutations) {
          lines.push(`    ${camel}: create${pascal}Sdk(client, optimistic),`);
        } else {
          lines.push(`    ${camel}: create${pascal}Sdk(client),`);
        }
      }
      for (const svc of services) {
        const pascal = toPascalCase(svc.serviceName);
        const camel = toCamelCase(svc.serviceName);
        lines.push(`    ${camel}: create${pascal}Sdk(client),`);
      }
      if (hasAuth) {
        lines.push('    auth,');
      }
      lines.push('  };');
    } else {
      lines.push('  return {};');
    }

    lines.push('}');
    lines.push('');
    lines.push('export type Client = ReturnType<typeof createClient>;');

    return { path: 'client.ts', content: lines.join('\n') };
  }

  private generatePackageJson(outputDir: string): GeneratedFile {
    // Normalize to posix forward slashes and ensure ./ prefix
    const dir = `./${posix.normalize(outputDir.replace(/\\/g, '/'))}`;
    const pkg = {
      imports: {
        '#generated': `${dir}/client.ts`,
        '#generated/types': `${dir}/types/index.ts`,
      },
    };

    return { path: 'package.json', content: `${JSON.stringify(pkg, null, 2)}\n` };
  }

  private generateReadme(ir: CodegenIR): GeneratedFile {
    const entities = ir.entities ?? [];
    const lines: string[] = [];

    lines.push('# Generated Client');
    lines.push('');
    lines.push('Auto-generated by `@vertz/codegen`. Do not edit manually.');
    lines.push('');
    lines.push('## Usage');
    lines.push('');
    lines.push('```typescript');
    lines.push("import { createClient } from '#generated';");
    lines.push('');
    lines.push('const api = createClient();');
    lines.push('```');
    lines.push('');
    lines.push('## Type Imports');
    lines.push('');
    lines.push('```typescript');
    lines.push("import type { ... } from '#generated/types';");
    lines.push('```');

    if (entities.length > 0) {
      lines.push('');
      lines.push('## Available Resources');
      lines.push('');
      for (const entity of entities) {
        const camel = toCamelCase(entity.entityName);
        const methods = this.getEntityMethods(entity);
        lines.push(`- \`client.${camel}\` — ${methods}`);
      }
    }

    lines.push('');

    return { path: 'README.md', content: lines.join('\n') };
  }

  private getEntityMethods(entity: CodegenEntityModule): string {
    const methods: string[] = [];
    for (const op of entity.operations) {
      methods.push(op.kind);
    }
    for (const action of entity.actions) {
      methods.push(action.name);
    }
    return methods.length > 0 ? methods.join(', ') : 'no operations';
  }
}
