import type {
  CodegenEntityModule,
  CodegenIR,
  CodegenResolvedField,
  GeneratedFile,
  Generator,
  GeneratorConfig,
} from '../types';

const FILE_HEADER = '// Generated by @vertz/codegen — do not edit\n\n';

const TYPE_MAP: Record<CodegenResolvedField['tsType'], { base: string; minOne: boolean }> = {
  string: { base: 's.string()', minOne: true },
  number: { base: 's.number()', minOne: false },
  boolean: { base: 's.boolean()', minOne: false },
  date: { base: 's.string()', minOne: true }, // JSON transport delivers ISO strings
  unknown: { base: 's.unknown()', minOne: false },
};

function toLowerFirst(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

export class EntitySchemaGenerator implements Generator {
  readonly name = 'entity-schema';

  generate(ir: CodegenIR, _config: GeneratorConfig): GeneratedFile[] {
    if (!ir.entities?.length) return [];

    const files: GeneratedFile[] = [];
    const entitiesWithSchemas: CodegenEntityModule[] = [];

    for (const entity of ir.entities) {
      const schemaOps = entity.operations.filter(
        (op) =>
          (op.kind === 'create' || op.kind === 'update') &&
          op.resolvedFields &&
          op.resolvedFields.length > 0,
      );

      const schemaActions = entity.actions.filter(
        (a) => a.resolvedInputFields && a.resolvedInputFields.length > 0,
      );

      if (schemaOps.length === 0 && schemaActions.length === 0) continue;

      entitiesWithSchemas.push(entity);
      files.push(this.generateEntitySchema(entity, schemaOps, schemaActions));
    }

    if (entitiesWithSchemas.length > 0) {
      files.push(this.generateIndex(entitiesWithSchemas));
    }

    return files;
  }

  private generateEntitySchema(
    entity: CodegenEntityModule,
    schemaOps: CodegenEntityModule['operations'],
    schemaActions: CodegenEntityModule['actions'],
  ): GeneratedFile {
    const lines: string[] = [FILE_HEADER];
    lines.push("import { s } from '@vertz/schema';");
    lines.push('');

    for (const op of schemaOps) {
      if (!op.resolvedFields) continue;

      const varName = `${toLowerFirst(op.inputSchema ?? `${op.kind}Input`)}Schema`;
      const fields = op.resolvedFields
        .map((f) => {
          const entry = TYPE_MAP[f.tsType] ?? { base: 's.unknown()', minOne: false };
          let call = entry.base;
          if (!f.optional && entry.minOne) call += '.min(1)';
          if (f.optional) call += '.optional()';
          return `  ${f.name}: ${call}`;
        })
        .join(',\n');

      lines.push(`export const ${varName} = s.object({`);
      lines.push(`${fields},`);
      lines.push('});');
      lines.push('');
    }

    for (const action of schemaActions) {
      if (!action.resolvedInputFields) continue;

      const varName = `${toLowerFirst(action.inputSchema ?? `${action.name}Input`)}Schema`;
      const fields = action.resolvedInputFields
        .map((f) => {
          const entry = TYPE_MAP[f.tsType] ?? { base: 's.unknown()', minOne: false };
          let call = entry.base;
          if (!f.optional && entry.minOne) call += '.min(1)';
          if (f.optional) call += '.optional()';
          return `  ${f.name}: ${call}`;
        })
        .join(',\n');

      lines.push(`export const ${varName} = s.object({`);
      lines.push(`${fields},`);
      lines.push('});');
      lines.push('');
    }

    return {
      path: `schemas/${entity.entityName}.ts`,
      content: lines.join('\n'),
    };
  }

  private generateIndex(entities: CodegenEntityModule[]): GeneratedFile {
    const lines: string[] = [FILE_HEADER];

    for (const entity of entities) {
      const exports: string[] = [];

      const schemaOps = entity.operations.filter(
        (op) =>
          (op.kind === 'create' || op.kind === 'update') &&
          op.resolvedFields &&
          op.resolvedFields.length > 0,
      );
      for (const op of schemaOps) {
        const varName = `${toLowerFirst(op.inputSchema ?? `${op.kind}Input`)}Schema`;
        exports.push(varName);
      }

      const schemaActions = entity.actions.filter(
        (a) => a.resolvedInputFields && a.resolvedInputFields.length > 0,
      );
      for (const action of schemaActions) {
        const varName = `${toLowerFirst(action.inputSchema ?? `${action.name}Input`)}Schema`;
        exports.push(varName);
      }

      if (exports.length > 0) {
        lines.push(`export { ${exports.join(', ')} } from './${entity.entityName}';`);
      }
    }

    return { path: 'schemas/index.ts', content: lines.join('\n') };
  }
}
