import type {
  CodegenEntityModule,
  CodegenIR,
  CodegenResolvedField,
  GeneratedFile,
  Generator,
  GeneratorConfig,
} from '../types';

const FILE_HEADER = '// Generated by @vertz/codegen — do not edit\n\n';

const TS_TYPE_MAP: Record<CodegenResolvedField['tsType'], string> = {
  string: 'string',
  number: 'number',
  boolean: 'boolean',
  date: 'string', // JSON transport delivers ISO strings
  unknown: 'unknown',
};

export class EntityTypesGenerator implements Generator {
  readonly name = 'entity-types';

  generate(ir: CodegenIR, _config: GeneratorConfig): GeneratedFile[] {
    if (!ir.entities?.length) return [];

    const files: GeneratedFile[] = [];
    const entitiesWithTypes: CodegenEntityModule[] = [];

    for (const entity of ir.entities) {
      const hasOpTypes = entity.operations.some((op) => op.inputSchema || op.outputSchema);
      const hasActionTypes = entity.actions.some(
        (a) => a.resolvedInputFields?.length || a.resolvedOutputFields?.length,
      );
      if (!hasOpTypes && !hasActionTypes) continue;

      entitiesWithTypes.push(entity);
      files.push(this.generateEntityTypes(entity));
    }

    if (entitiesWithTypes.length > 0) {
      files.push(this.generateIndex(entitiesWithTypes));
    }

    return files;
  }

  private generateEntityTypes(entity: CodegenEntityModule): GeneratedFile {
    const lines: string[] = [FILE_HEADER];

    // Collect unique type names already emitted to avoid duplicates
    const emitted = new Set<string>();

    for (const op of entity.operations) {
      // Emit input type (body type for create/update)
      if (op.inputSchema && !emitted.has(op.inputSchema)) {
        const inputType = this.emitBodyType(op.inputSchema, op.resolvedFields);
        if (inputType) {
          lines.push(inputType);
          lines.push('');
          emitted.add(op.inputSchema);
        }
      }

      // Emit output type (response type)
      if (op.outputSchema && !emitted.has(op.outputSchema)) {
        const outputType = this.emitResponseType(op.outputSchema, op.responseFields, entity);
        if (outputType) {
          lines.push(outputType);
          lines.push('');
          emitted.add(op.outputSchema);
        }
      }
    }

    // Emit Fields type alias for response types (enables SDK select narrowing)
    const responseSchema = entity.operations.find(
      (op) => (op.kind === 'list' || op.kind === 'get') && op.outputSchema,
    )?.outputSchema;
    if (responseSchema && !emitted.has(`${responseSchema}Fields`)) {
      const fieldsTypeName = responseSchema.replace(/Response$/, 'Fields');
      lines.push(`export type ${fieldsTypeName} = keyof ${responseSchema};`);
      lines.push('');
      emitted.add(`${responseSchema}Fields`);
    }

    // Emit query types (WhereInput, OrderByInput)
    const entityPascal = entity.entityName.charAt(0).toUpperCase() + entity.entityName.slice(1);

    if (entity.allowWhere?.length) {
      const whereType = this.emitWhereInput(`${entityPascal}WhereInput`, entity.allowWhere);
      lines.push(whereType);
      lines.push('');
    }

    if (entity.allowOrderBy?.length) {
      const orderByType = this.emitOrderByInput(`${entityPascal}OrderByInput`, entity.allowOrderBy);
      lines.push(orderByType);
      lines.push('');
    }

    if (entity.exposeInclude?.length) {
      const includeType = this.emitIncludeInput(
        `${entityPascal}IncludeInput`,
        entity.exposeInclude,
        entity.relationQueryConfig,
      );
      lines.push(includeType);
      lines.push('');
    }

    // Emit ListQuery and GetQuery (only when entity has expose config)
    if (entity.exposeSelect) {
      const selectType = this.emitSelectType(entity.responseFields);
      const hasWhere = !!entity.allowWhere?.length;
      const hasOrderBy = !!entity.allowOrderBy?.length;
      const hasInclude = !!entity.exposeInclude?.length;

      const hasList = entity.operations.some((op) => op.kind === 'list');
      const hasGet = entity.operations.some((op) => op.kind === 'get');

      if (hasList) {
        lines.push(
          this.emitListQuery(entityPascal, selectType, hasWhere, hasOrderBy, hasInclude),
        );
        lines.push('');
      }
      if (hasGet) {
        lines.push(this.emitGetQuery(entityPascal, selectType, hasInclude));
        lines.push('');
      }
    }

    // Emit action input/output types
    for (const action of entity.actions) {
      if (action.inputSchema && !emitted.has(action.inputSchema)) {
        const inputType = this.emitBodyType(action.inputSchema, action.resolvedInputFields);
        if (inputType) {
          lines.push(inputType);
          lines.push('');
          emitted.add(action.inputSchema);
        }
      }

      if (action.outputSchema && !emitted.has(action.outputSchema)) {
        // Action output types don't get expose logic (T|null, relations) — those are entity-specific
        const outputType = this.emitBodyType(action.outputSchema, action.resolvedOutputFields);
        if (outputType) {
          lines.push(outputType);
          lines.push('');
          emitted.add(action.outputSchema);
        }
      }
    }

    return {
      path: `types/${entity.entityName}.ts`,
      content: lines.join('\n'),
    };
  }

  private emitBodyType(
    typeName: string,
    fields: CodegenResolvedField[] | undefined,
  ): string | undefined {
    if (!fields || fields.length === 0) return undefined;

    const props = fields
      .map((f) => {
        const tsType = TS_TYPE_MAP[f.tsType] ?? 'unknown';
        const optional = f.optional ? '?' : '';
        return `  ${f.name}${optional}: ${tsType}`;
      })
      .join(';\n');

    return `export interface ${typeName} {\n${props};\n}`;
  }

  private emitResponseType(
    typeName: string,
    fields: CodegenResolvedField[] | undefined,
    entity: CodegenEntityModule,
  ): string | undefined {
    if (!fields || fields.length === 0) return undefined;

    // Build a set of conditional field names for T | null emission
    const conditionalFields = new Set(
      entity.exposeSelect?.filter((f) => f.conditional).map((f) => f.name) ?? [],
    );

    const props = fields
      .map((f) => {
        const tsType = TS_TYPE_MAP[f.tsType] ?? 'unknown';
        const optional = f.optional ? '?' : '';
        const nullable = conditionalFields.has(f.name) ? ' | null' : '';
        return `  ${f.name}${optional}: ${tsType}${nullable}`;
      })
      .join(';\n');

    // Add relation properties from exposeInclude
    const relationProps: string[] = [];
    if (entity.exposeInclude) {
      for (const rel of entity.exposeInclude) {
        if (!rel.resolvedFields || rel.resolvedFields.length === 0) continue;

        const relFields = rel.resolvedFields
          .map((f) => {
            const tsType = TS_TYPE_MAP[f.tsType] ?? 'unknown';
            return `${f.name}: ${tsType}`;
          })
          .join('; ');

        if (rel.type === 'many') {
          relationProps.push(`  ${rel.name}: Array<{ ${relFields} }>`);
        } else {
          relationProps.push(`  ${rel.name}?: { ${relFields} }`);
        }
      }
    }

    const allProps = relationProps.length > 0 ? `${props};\n${relationProps.join(';\n')}` : props;

    return `export interface ${typeName} {\n${allProps};\n}`;
  }

  private emitWhereInput(
    typeName: string,
    fields: Array<{ name: string; tsType: CodegenResolvedField['tsType'] }>,
  ): string {
    const props = fields
      .map((f) => {
        const tsType = TS_TYPE_MAP[f.tsType] ?? 'unknown';
        return `  ${f.name}?: ${tsType} | { ${this.whereOperators(f.tsType, tsType)} }`;
      })
      .join(';\n');

    return `export interface ${typeName} {\n${props};\n}`;
  }

  private whereOperators(
    tsType: CodegenResolvedField['tsType'],
    mapped: string,
  ): string {
    const ops: string[] = [`eq?: ${mapped}`, `neq?: ${mapped}`];
    if (tsType === 'string') {
      ops.push(`in?: ${mapped}[]`, `like?: ${mapped}`, `contains?: ${mapped}`);
    } else if (tsType === 'number' || tsType === 'date') {
      ops.push(
        `gt?: ${mapped}`,
        `lt?: ${mapped}`,
        `gte?: ${mapped}`,
        `lte?: ${mapped}`,
        `in?: ${mapped}[]`,
      );
    } else if (tsType === 'boolean') {
      // only eq/neq
    } else {
      ops.push(`in?: ${mapped}[]`);
    }
    return ops.join('; ');
  }

  private emitOrderByInput(typeName: string, fields: string[]): string {
    const props = fields.map((f) => `  ${f}?: 'asc' | 'desc'`).join(';\n');
    return `export interface ${typeName} {\n${props};\n}`;
  }

  private emitIncludeInput(
    typeName: string,
    includes: NonNullable<CodegenEntityModule['exposeInclude']>,
    queryConfig?: CodegenEntityModule['relationQueryConfig'],
  ): string {
    const props = includes
      .map((rel) => {
        const config = queryConfig?.[rel.name];
        const hasSelect = !!rel.select?.length;
        const hasQueryConfig = !!config;

        if (!hasSelect && !hasQueryConfig) {
          return `  ${rel.name}?: true`;
        }

        const parts: string[] = [];
        if (hasSelect) {
          const selectFields = rel.select!.map((f) => `${f.name}?: true`).join('; ');
          parts.push(`select?: { ${selectFields} }`);
        }
        if (config?.allowWhere?.length && rel.resolvedFields) {
          const fieldMap = new Map(rel.resolvedFields.map((f) => [f.name, f.tsType]));
          const whereFields = config.allowWhere
            .filter((name) => fieldMap.has(name))
            .map((name) => {
              const tsType = fieldMap.get(name)!;
              const mapped = TS_TYPE_MAP[tsType] ?? 'unknown';
              return `${name}?: ${mapped} | { ${this.whereOperators(tsType, mapped)} }`;
            });
          if (whereFields.length > 0) {
            parts.push(`where?: { ${whereFields.join('; ')} }`);
          }
        }
        if (config?.allowOrderBy?.length) {
          const orderFields = config.allowOrderBy
            .map((f) => `${f}?: 'asc' | 'desc'`)
            .join('; ');
          parts.push(`orderBy?: { ${orderFields} }`);
        }
        if (config?.maxLimit !== undefined) {
          parts.push('limit?: number');
        }

        return `  ${rel.name}?: true | { ${parts.join('; ')} }`;
      })
      .join(';\n');

    return `export interface ${typeName} {\n${props};\n}`;
  }

  private emitSelectType(fields: CodegenResolvedField[] | undefined): string {
    if (!fields?.length) return '{}';
    return `{ ${fields.map((f) => `${f.name}?: true`).join('; ')} }`;
  }

  private emitListQuery(
    entityPascal: string,
    selectType: string,
    hasWhere: boolean,
    hasOrderBy: boolean,
    hasInclude: boolean,
  ): string {
    const props: string[] = [`  select?: ${selectType}`];
    if (hasWhere) props.push(`  where?: ${entityPascal}WhereInput`);
    if (hasOrderBy) props.push(`  orderBy?: ${entityPascal}OrderByInput`);
    if (hasInclude) props.push(`  include?: ${entityPascal}IncludeInput`);
    props.push('  limit?: number');
    props.push('  after?: string');
    return `export interface ${entityPascal}ListQuery {\n${props.join(';\n')};\n}`;
  }

  private emitGetQuery(
    entityPascal: string,
    selectType: string,
    hasInclude: boolean,
  ): string {
    const props: string[] = [`  select?: ${selectType}`];
    if (hasInclude) props.push(`  include?: ${entityPascal}IncludeInput`);
    return `export interface ${entityPascal}GetQuery {\n${props.join(';\n')};\n}`;
  }

  private generateIndex(entities: CodegenEntityModule[]): GeneratedFile {
    const lines: string[] = [FILE_HEADER];

    for (const entity of entities) {
      lines.push(`export * from './${entity.entityName}';`);
    }

    return { path: 'types/index.ts', content: lines.join('\n') };
  }
}
