import type {
  CodegenAccess,
  CodegenIR,
  CodegenWhereCondition,
  GeneratedFile,
  Generator,
  GeneratorConfig,
} from '../types';

const FILE_HEADER = '-- Generated by @vertz/codegen — do not edit\n\n';

export class RlsPolicyGenerator implements Generator {
  readonly name = 'rls-policies';

  generate(ir: CodegenIR, _config: GeneratorConfig): GeneratedFile[] {
    if (!ir.access || ir.access.whereClauses.length === 0) {
      return [];
    }

    return [
      {
        path: 'rls-policies.sql',
        content: renderPolicies(ir.access),
      },
    ];
  }
}

function toSnakeCase(str: string): string {
  return str.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
}

function renderCondition(condition: CodegenWhereCondition): string {
  const column = toSnakeCase(condition.column);

  if (condition.kind === 'marker') {
    if (condition.marker === 'user.id') {
      return `${column} = current_setting('app.user_id')::UUID`;
    }
    return `${column} = current_setting('app.tenant_id')::UUID`;
  }

  // Literal
  if (typeof condition.value === 'string') {
    const escaped = condition.value.replace(/'/g, "''");
    return `${column} = '${escaped}'`;
  }
  return `${column} = ${condition.value}`;
}

function renderPolicies(access: CodegenAccess): string {
  const lines: string[] = [FILE_HEADER];

  for (const clause of access.whereClauses) {
    const policyName = clause.entitlement.replace(/:/g, '_');

    lines.push(`-- Entitlement: ${clause.entitlement}`);

    const using = clause.conditions.map(renderCondition).join(' AND ');

    lines.push(`CREATE POLICY ${policyName} ON ${policyName.split('_')[0]}s FOR ALL`);
    lines.push(`  USING (${using});`);
    lines.push('');
  }

  return lines.join('\n');
}
