import type {
  CodegenAccess,
  CodegenIR,
  CodegenWhereCondition,
  GeneratedFile,
  Generator,
  GeneratorConfig,
} from '../types';
import { toSnakeCase } from '../utils/naming';

const FILE_HEADER = '-- Generated by @vertz/codegen — do not edit\n\n';
const VALID_IDENTIFIER = /^[a-zA-Z_][a-zA-Z0-9_]*$/;

export class RlsPolicyGenerator implements Generator {
  readonly name = 'rls-policies';

  generate(ir: CodegenIR, _config: GeneratorConfig): GeneratedFile[] {
    if (!ir.access || ir.access.whereClauses.length === 0) {
      return [];
    }

    return [
      {
        path: 'rls-policies.sql',
        content: renderPolicies(ir.access),
      },
    ];
  }
}

function quoteIdentifier(name: string): string {
  if (!VALID_IDENTIFIER.test(name)) {
    return `"${name.replace(/"/g, '""')}"`;
  }
  return name;
}

function renderCondition(condition: CodegenWhereCondition): string {
  const column = quoteIdentifier(toSnakeCase(condition.column));

  if (condition.kind === 'marker') {
    if (condition.marker === 'user.id') {
      return `${column} = current_setting('app.user_id')::UUID`;
    }
    return `${column} = current_setting('app.tenant_id')::UUID`;
  }

  // Literal
  if (typeof condition.value === 'string') {
    const escaped = condition.value.replace(/'/g, "''");
    return `${column} = '${escaped}'`;
  }
  return `${column} = ${condition.value}`;
}

function renderPolicies(access: CodegenAccess): string {
  const lines: string[] = [FILE_HEADER];

  for (const clause of access.whereClauses) {
    // Split entitlement on ':' to get entity and action
    const colonIdx = clause.entitlement.indexOf(':');
    const entity = colonIdx >= 0 ? clause.entitlement.slice(0, colonIdx) : clause.entitlement;
    const action = colonIdx >= 0 ? clause.entitlement.slice(colonIdx + 1) : '';

    const tableName = quoteIdentifier(`${toSnakeCase(entity)}s`);
    const policyName = quoteIdentifier(
      `${toSnakeCase(entity)}_${toSnakeCase(action)}`.replace(/^_+|_+$/g, ''),
    );

    lines.push(`-- Entitlement: ${clause.entitlement}`);

    const using = clause.conditions.map(renderCondition).join(' AND ');

    lines.push(`CREATE POLICY ${policyName} ON ${tableName} FOR ALL`);
    lines.push(`  USING (${using});`);
    lines.push('');
  }

  return lines.join('\n');
}
