import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { dirname, extname, join, relative, resolve, sep } from 'node:path';
import type { CodegenIR, GeneratedFile, Generator, GeneratorConfig } from '../types';

const FILE_HEADER = '// Generated by @vertz/codegen — do not edit\n\n';
const CANDIDATE_ROUTE_FILES = [
  ['src', 'router.ts'],
  ['src', 'router.tsx'],
  ['src', 'ui', 'router.ts'],
  ['src', 'ui', 'router.tsx'],
];
const SOURCE_EXTENSIONS = new Set(['.ts', '.tsx']);
const EXPORTED_ROUTES_PATTERN = /export\s+const\s+routes\b/m;
const REEXPORTED_ROUTES_PATTERN = /const\s+routes\b[\s\S]*?export\s*\{\s*routes\b/m;

export class RouterAugmentationGenerator implements Generator {
  readonly name = 'router-augmentation';

  generate(_ir: CodegenIR, config: GeneratorConfig): GeneratedFile[] {
    const projectRoot = findProjectRoot(config.outputDir);
    if (!projectRoot) return [];

    const routeModulePath = findRouteModule(projectRoot);
    if (!routeModulePath) return [];

    return [
      {
        path: 'router.d.ts',
        content: renderRouterAugmentation(routeModulePath, config.outputDir),
      },
    ];
  }
}

function findProjectRoot(outputDir: string): string | null {
  let current = resolve(outputDir);

  while (true) {
    if (existsSync(join(current, 'package.json'))) {
      return current;
    }

    const parent = dirname(current);
    if (parent === current) {
      return null;
    }

    current = parent;
  }
}

function findRouteModule(projectRoot: string): string | null {
  for (const candidate of CANDIDATE_ROUTE_FILES) {
    const candidatePath = join(projectRoot, ...candidate);
    if (existsSync(candidatePath) && fileExportsRoutes(candidatePath)) {
      return candidatePath;
    }
  }

  return scanForRouteModule(join(projectRoot, 'src'));
}

function scanForRouteModule(dir: string): string | null {
  if (!existsSync(dir)) return null;

  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, entry.name);

    if (entry.isDirectory()) {
      const nested = scanForRouteModule(fullPath);
      if (nested) {
        return nested;
      }
      continue;
    }

    if (!entry.isFile()) continue;

    const extension = extname(entry.name);
    if (extension === '.d.ts' || !SOURCE_EXTENSIONS.has(extension)) continue;

    if (fileExportsRoutes(fullPath)) {
      return fullPath;
    }
  }

  return null;
}

function fileExportsRoutes(filePath: string): boolean {
  const source = readFileSync(filePath, 'utf-8');
  if (!source.includes('defineRoutes(')) return false;

  return EXPORTED_ROUTES_PATTERN.test(source) || REEXPORTED_ROUTES_PATTERN.test(source);
}

function renderRouterAugmentation(routeModulePath: string, outputDir: string): string {
  const importPath = toImportPath(relative(resolve(outputDir), routeModulePath));

  return [
    FILE_HEADER,
    'import type {',
    '  ExtractSearchParams,',
    '  InferRouteMap,',
    '  ReactiveSearchParams,',
    '  RoutePattern,',
    '  TypedRouter,',
    '  UnwrapSignals,',
    "} from '@vertz/ui';",
    `import type { routes } from '${importPath}';`,
    '',
    'type AppRouteMap = InferRouteMap<typeof routes>;',
    '',
    "declare module '@vertz/ui' {",
    '  export function useRouter(): UnwrapSignals<TypedRouter<AppRouteMap>>;',
    '  export function useSearchParams<',
    '    TPath extends RoutePattern<AppRouteMap>,',
    '  >(): ReactiveSearchParams<ExtractSearchParams<TPath, AppRouteMap>>;',
    '}',
    '',
    "declare module '@vertz/ui/router' {",
    '  export function useRouter(): UnwrapSignals<TypedRouter<AppRouteMap>>;',
    '  export function useSearchParams<',
    '    TPath extends RoutePattern<AppRouteMap>,',
    '  >(): ReactiveSearchParams<ExtractSearchParams<TPath, AppRouteMap>>;',
    '}',
    '',
  ].join('\n');
}

function toImportPath(pathToModule: string): string {
  const normalized = pathToModule.split(sep).join('/');
  const withoutExtension = normalized.replace(/\.[^.]+$/, '');
  return withoutExtension.startsWith('.') ? withoutExtension : `./${withoutExtension}`;
}
