import type {
  CodegenIR,
  CodegenResolvedField,
  CodegenServiceModule,
  GeneratedFile,
  Generator,
  GeneratorConfig,
} from '../types';

const FILE_HEADER = '// Generated by @vertz/codegen — do not edit\n\n';

const TS_TYPE_MAP: Record<CodegenResolvedField['tsType'], string> = {
  string: 'string',
  number: 'number',
  boolean: 'boolean',
  date: 'string',
  unknown: 'unknown',
};

export class ServiceTypesGenerator implements Generator {
  readonly name = 'service-types';

  generate(ir: CodegenIR, _config: GeneratorConfig): GeneratedFile[] {
    const services = (ir.services ?? []).filter((s) =>
      s.actions.some((a) => a.resolvedInputFields?.length || a.resolvedOutputFields?.length),
    );
    if (!services.length) return [];
    return services.map((s) => this.generateServiceTypes(s));
  }

  private generateServiceTypes(svc: CodegenServiceModule): GeneratedFile {
    const lines: string[] = [FILE_HEADER];
    const emitted = new Set<string>();

    for (const action of svc.actions) {
      if (action.inputSchema && action.resolvedInputFields?.length && !emitted.has(action.inputSchema)) {
        lines.push(this.emitInterface(action.inputSchema, action.resolvedInputFields));
        lines.push('');
        emitted.add(action.inputSchema);
      }
      if (
        action.outputSchema &&
        action.resolvedOutputFields?.length &&
        !emitted.has(action.outputSchema)
      ) {
        lines.push(this.emitInterface(action.outputSchema, action.resolvedOutputFields));
        lines.push('');
        emitted.add(action.outputSchema);
      }
    }

    return {
      path: `types/services/${svc.serviceName}.ts`,
      content: lines.join('\n'),
    };
  }

  private emitInterface(typeName: string, fields: CodegenResolvedField[]): string {
    const props = fields
      .map((f) => {
        const tsType = TS_TYPE_MAP[f.tsType] ?? 'unknown';
        const optional = f.optional ? '?' : '';
        return `  ${f.name}${optional}: ${tsType}`;
      })
      .join(';\n');
    return `export interface ${typeName} {\n${props};\n}`;
  }
}
