import type {
  CodegenIR,
  CodegenServiceModule,
  GeneratedFile,
  Generator,
  GeneratorConfig,
} from '../types';
import { toPascalCase } from '../utils/naming';

const FILE_HEADER = '// Generated by @vertz/codegen — do not edit\n\n';

const PATH_PARAM_RE = /:(\w+)/g;

const MUTATION_METHODS = new Set(['POST', 'PUT', 'PATCH', 'DELETE']);

function isMutation(method: string): boolean {
  return MUTATION_METHODS.has(method);
}

function mutationKind(method: string): 'create' | 'update' | 'delete' {
  if (method === 'POST') return 'create';
  if (method === 'DELETE') return 'delete';
  return 'update';
}

/** Convert `:param` path syntax to `{param}` for queryKey() */
function toQueryKeyPath(path: string): string {
  return path.replace(PATH_PARAM_RE, '{$1}');
}

export class ServiceSdkGenerator implements Generator {
  readonly name = 'service-sdk';

  generate(ir: CodegenIR, _config: GeneratorConfig): GeneratedFile[] {
    const servicesWithActions = (ir.services ?? []).filter((s) => s.actions.length > 0);
    if (!servicesWithActions.length) return [];

    const files: GeneratedFile[] = [];

    for (const svc of servicesWithActions) {
      files.push(this.generateServiceSdk(svc));
    }

    files.push(this.generateIndex(servicesWithActions));

    return files;
  }

  private generateServiceSdk(svc: CodegenServiceModule): GeneratedFile {
    const pascal = toPascalCase(svc.serviceName);
    const lines: string[] = [FILE_HEADER];

    const hasQuery = svc.actions.some((a) => !isMutation(a.method));
    const hasMutation = svc.actions.some((a) => isMutation(a.method));

    // Build import parts
    const importParts: string[] = ['type FetchClient'];
    if (hasQuery) importParts.push('createDescriptor');
    if (hasMutation) importParts.push('createMutationDescriptor');
    importParts.push('queryKey');

    lines.push(`import { ${importParts.join(', ')} } from '@vertz/fetch';`);
    lines.push('');
    lines.push(`export function create${pascal}Sdk(client: FetchClient) {`);
    lines.push('  return {');

    for (const action of svc.actions) {
      const method = action.method;
      const methodLower = method.toLowerCase();
      const hasBody = method === 'POST' || method === 'PUT' || method === 'PATCH';
      const isMut = isMutation(method);

      // Extract path parameters (e.g., :messageId -> messageId)
      const pathParams: string[] = [];
      let match: RegExpExecArray | null = null;
      PATH_PARAM_RE.lastIndex = 0;
      while ((match = PATH_PARAM_RE.exec(action.path)) !== null) {
        pathParams.push(match[1]);
      }

      const hasPathParams = pathParams.length > 0;
      const pathExpr = hasPathParams
        ? `\`${action.path.replace(PATH_PARAM_RE, '${$1}')}\``
        : `'${action.path}'`;

      // Build method parameters
      const params: string[] = [];
      for (const p of pathParams) {
        params.push(`${p}: string`);
      }
      if (hasBody) params.push('body: unknown');
      const paramStr = params.join(', ');

      const clientArgs = hasBody ? `${pathExpr}, body` : pathExpr;
      const clientCall = `client.${methodLower}<unknown>(${clientArgs})`;

      // Build queryKey parameters (same as path params, but all optional)
      const queryKeyParamStr = pathParams.map((p) => `${p}?: string`).join(', ');
      const queryKeyPath = toQueryKeyPath(action.path);
      let queryKeyExpr: string;
      if (hasPathParams) {
        const paramsObj = pathParams.join(', ');
        queryKeyExpr = `(${queryKeyParamStr}) => queryKey({ path: '${queryKeyPath}', params: { ${paramsObj} } })`;
      } else {
        queryKeyExpr = `() => queryKey({ path: '${queryKeyPath}' })`;
      }

      lines.push(`    ${action.name}: Object.assign(`);

      if (isMut) {
        // Build MutationMeta
        const metaParts: string[] = [
          `entityType: '${svc.serviceName}'`,
          `kind: '${mutationKind(method)}' as const`,
        ];
        // First path param is treated as id
        if (pathParams.length > 0) {
          metaParts.push(`id: ${pathParams[0]}`);
        }
        if (hasBody) {
          metaParts.push('body');
        }

        lines.push(
          `      (${paramStr}) => createMutationDescriptor('${method}', ${pathExpr}, () => ${clientCall}, { ${metaParts.join(', ')} }),`,
        );
      } else {
        lines.push(
          `      (${paramStr}) => createDescriptor('${method}', ${pathExpr}, () => ${clientCall}),`,
        );
      }

      lines.push(`      {`);
      lines.push(`        url: '${action.path}',`);
      lines.push(`        method: '${method}' as const,`);
      lines.push(`        queryKey: ${queryKeyExpr},`);
      lines.push(`      },`);
      lines.push('    ),');
    }

    lines.push('  };');
    lines.push('}');

    return {
      path: `services/${svc.serviceName}.ts`,
      content: lines.join('\n'),
    };
  }

  private generateIndex(services: CodegenServiceModule[]): GeneratedFile {
    const lines: string[] = [FILE_HEADER];
    for (const svc of services) {
      const pascal = toPascalCase(svc.serviceName);
      lines.push(`export { create${pascal}Sdk } from './${svc.serviceName}';`);
    }
    return { path: 'services/index.ts', content: lines.join('\n') };
  }
}
