import type {
  CodegenIR,
  CodegenServiceModule,
  GeneratedFile,
  Generator,
  GeneratorConfig,
} from '../types';

const FILE_HEADER = '// Generated by @vertz/codegen — do not edit\n\n';

function toPascalCase(s: string): string {
  return s
    .split('-')
    .map((w) => w[0]?.toUpperCase() + w.slice(1))
    .join('');
}

export class ServiceSdkGenerator implements Generator {
  readonly name = 'service-sdk';

  generate(ir: CodegenIR, _config: GeneratorConfig): GeneratedFile[] {
    const servicesWithActions = (ir.services ?? []).filter((s) => s.actions.length > 0);
    if (!servicesWithActions.length) return [];

    const files: GeneratedFile[] = [];

    for (const svc of servicesWithActions) {
      files.push(this.generateServiceSdk(svc));
    }

    files.push(this.generateIndex(servicesWithActions));

    return files;
  }

  private generateServiceSdk(svc: CodegenServiceModule): GeneratedFile {
    const pascal = toPascalCase(svc.serviceName);
    const lines: string[] = [FILE_HEADER];

    lines.push("import { type FetchClient, createDescriptor } from '@vertz/fetch';");
    lines.push('');
    lines.push(`export function create${pascal}Sdk(client: FetchClient) {`);
    lines.push('  return {');

    for (const action of svc.actions) {
      const method = action.method;
      const methodLower = method.toLowerCase();
      const hasBody = method === 'POST' || method === 'PUT' || method === 'PATCH';

      const params: string[] = [];
      if (hasBody) params.push('body: unknown');
      const paramStr = params.join(', ');

      const clientArgs = hasBody ? `'${action.path}', body` : `'${action.path}'`;
      const clientCall = `client.${methodLower}<unknown>(${clientArgs})`;

      lines.push(`    ${action.name}: Object.assign(`);
      lines.push(
        `      (${paramStr}) => createDescriptor('${method}', '${action.path}', () => ${clientCall}${hasBody ? ', body' : ''}),`,
      );
      lines.push(`      { url: '${action.path}', method: '${method}' as const },`);
      lines.push('    ),');
    }

    lines.push('  };');
    lines.push('}');

    return {
      path: `services/${svc.serviceName}.ts`,
      content: lines.join('\n'),
    };
  }

  private generateIndex(services: CodegenServiceModule[]): GeneratedFile {
    const lines: string[] = [FILE_HEADER];
    for (const svc of services) {
      const pascal = toPascalCase(svc.serviceName);
      lines.push(`export { create${pascal}Sdk } from './${svc.serviceName}';`);
    }
    return { path: 'services/index.ts', content: lines.join('\n') };
  }
}
