import type {
  CodegenIR,
  CodegenServiceModule,
  GeneratedFile,
  Generator,
  GeneratorConfig,
} from '../types';
import { toPascalCase } from '../utils/naming';

const FILE_HEADER = '// Generated by @vertz/codegen — do not edit\n\n';

const PATH_PARAM_RE = /:(\w+)/g;

export class ServiceSdkGenerator implements Generator {
  readonly name = 'service-sdk';

  generate(ir: CodegenIR, _config: GeneratorConfig): GeneratedFile[] {
    const servicesWithActions = (ir.services ?? []).filter((s) => s.actions.length > 0);
    if (!servicesWithActions.length) return [];

    const files: GeneratedFile[] = [];

    for (const svc of servicesWithActions) {
      files.push(this.generateServiceSdk(svc));
    }

    files.push(this.generateIndex(servicesWithActions));

    return files;
  }

  private generateServiceSdk(svc: CodegenServiceModule): GeneratedFile {
    const pascal = toPascalCase(svc.serviceName);
    const lines: string[] = [FILE_HEADER];

    lines.push("import { type FetchClient, createDescriptor } from '@vertz/fetch';");
    lines.push('');
    lines.push(`export function create${pascal}Sdk(client: FetchClient) {`);
    lines.push('  return {');

    for (const action of svc.actions) {
      const method = action.method;
      const methodLower = method.toLowerCase();
      const hasBody = method === 'POST' || method === 'PUT' || method === 'PATCH';

      // Extract path parameters (e.g., :messageId -> messageId)
      const pathParams: string[] = [];
      let match: RegExpExecArray | null = null;
      PATH_PARAM_RE.lastIndex = 0;
      while ((match = PATH_PARAM_RE.exec(action.path)) !== null) {
        pathParams.push(match[1]);
      }

      const hasPathParams = pathParams.length > 0;
      const pathExpr = hasPathParams
        ? `\`${action.path.replace(PATH_PARAM_RE, '${$1}')}\``
        : `'${action.path}'`;

      const params: string[] = [];
      for (const p of pathParams) {
        params.push(`${p}: string`);
      }
      if (hasBody) params.push('body: unknown');
      const paramStr = params.join(', ');

      const clientArgs = hasBody ? `${pathExpr}, body` : pathExpr;
      const clientCall = `client.${methodLower}<unknown>(${clientArgs})`;

      lines.push(`    ${action.name}: Object.assign(`);
      lines.push(
        `      (${paramStr}) => createDescriptor('${method}', ${pathExpr}, () => ${clientCall}${hasBody ? ', body' : ''}),`,
      );
      lines.push(`      { url: '${action.path}', method: '${method}' as const },`);
      lines.push('    ),');
    }

    lines.push('  };');
    lines.push('}');

    return {
      path: `services/${svc.serviceName}.ts`,
      content: lines.join('\n'),
    };
  }

  private generateIndex(services: CodegenServiceModule[]): GeneratedFile {
    const lines: string[] = [FILE_HEADER];
    for (const svc of services) {
      const pascal = toPascalCase(svc.serviceName);
      lines.push(`export { create${pascal}Sdk } from './${svc.serviceName}';`);
    }
    return { path: 'services/index.ts', content: lines.join('\n') };
  }
}
