import { describe, expect, it } from 'bun:test';
import type { CodegenIR } from '../../types';
import { AccessTypesGenerator } from '../access-types-generator';

function createEmptyIR(): CodegenIR {
  return {
    auth: { schemes: [] },
    basePath: '/api',
    entities: [],
    modules: [],
    schemas: [],
  };
}

function getContent(generator: AccessTypesGenerator, ir: CodegenIR): string {
  const files = generator.generate(ir, { outputDir: '.vertz/generated', options: {} });
  expect(files).toHaveLength(1);
  return files[0].content;
}

describe('AccessTypesGenerator', () => {
  const generator = new AccessTypesGenerator();

  it('returns no files when access is undefined', () => {
    const ir = createEmptyIR();
    const files = generator.generate(ir, { outputDir: '.vertz/generated', options: {} });
    expect(files).toEqual([]);
  });

  it('returns no files when access has no entitlements', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: { entities: [], entitlements: [] },
    };
    const files = generator.generate(ir, { outputDir: '.vertz/generated', options: {} });
    expect(files).toEqual([]);
  });

  it('generates access.d.ts with EntitlementRegistry augmentation', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [{ name: 'workspace', roles: ['admin', 'member'] }],
        entitlements: ['workspace:invite', 'workspace:manage'],
      },
    };
    const files = generator.generate(ir, { outputDir: '.vertz/generated', options: {} });
    expect(files).toHaveLength(1);
    expect(files[0].path).toBe('access.d.ts');

    const content = files[0].content;
    expect(content).toContain('interface EntitlementRegistry');
    expect(content).toContain("'workspace:invite': true;");
    expect(content).toContain("'workspace:manage': true;");
  });

  it('augments both @vertz/server and @vertz/ui/auth', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [],
        entitlements: ['post:view'],
      },
    };
    const content = getContent(generator, ir);
    expect(content).toContain("declare module '@vertz/server'");
    expect(content).toContain("declare module '@vertz/ui/auth'");
    // Should NOT augment @vertz/ui (only @vertz/ui/auth)
    expect(content).not.toMatch(/declare module '@vertz\/ui'\s*\{/);
  });

  it('generates ResourceType union from entity names', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [
          { name: 'workspace', roles: ['admin'] },
          { name: 'project', roles: ['manager'] },
        ],
        entitlements: ['workspace:invite'],
      },
    };
    const content = getContent(generator, ir);
    expect(content).toContain("type ResourceType = 'workspace' | 'project';");
  });

  it('generates Role<T> conditional type from entity roles', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [
          { name: 'workspace', roles: ['admin', 'member'] },
          { name: 'project', roles: ['manager', 'contributor', 'viewer'] },
        ],
        entitlements: ['workspace:invite'],
      },
    };
    const content = getContent(generator, ir);
    expect(content).toContain("T extends 'workspace' ? 'admin' | 'member'");
    expect(content).toContain("T extends 'project' ? 'manager' | 'contributor' | 'viewer'");
    expect(content).toContain('never;');
  });

  it('generates file header', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [],
        entitlements: ['post:view'],
      },
    };
    const content = getContent(generator, ir);
    expect(content).toStartWith('// Generated by @vertz/codegen');
  });

  it('skips Role<T> when no entities have roles', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [],
        entitlements: ['global:admin'],
      },
    };
    const content = getContent(generator, ir);
    expect(content).not.toContain('type Role');
    expect(content).not.toContain('type ResourceType');
  });

  it('escapes single quotes in entitlement names', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [],
        entitlements: ["it's:allowed"],
      },
    };
    const content = getContent(generator, ir);
    expect(content).toContain("'it\\'s:allowed': true;");
  });

  it('escapes backslashes in entity names and roles', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [{ name: 'ns\\entity', roles: ['role\\1'] }],
        entitlements: ['some:ent'],
      },
    };
    const content = getContent(generator, ir);
    expect(content).toContain("'ns\\\\entity'");
    expect(content).toContain("'role\\\\1'");
  });

  it('skips entities with empty roles from Role<T>', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [
          { name: 'workspace', roles: ['admin'] },
          { name: 'project', roles: [] },
        ],
        entitlements: ['workspace:invite'],
      },
    };
    const content = getContent(generator, ir);
    expect(content).toContain("type ResourceType = 'workspace';");
    expect(content).not.toContain("'project'");
  });
});
