import { describe, expect, it } from 'bun:test';
import type { CodegenIR } from '../../types';
import { AccessTypesGenerator } from '../access-types-generator';

function createEmptyIR(): CodegenIR {
  return {
    auth: { schemes: [] },
    basePath: '/api',
    entities: [],
    modules: [],
    schemas: [],
  };
}

describe('AccessTypesGenerator', () => {
  const generator = new AccessTypesGenerator();

  it('returns no files when access is undefined', () => {
    const ir = createEmptyIR();
    const files = generator.generate(ir, { outputDir: '.vertz/generated', options: {} });
    expect(files).toEqual([]);
  });

  it('returns no files when access has no entitlements', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: { entities: [], entitlements: [] },
    };
    const files = generator.generate(ir, { outputDir: '.vertz/generated', options: {} });
    expect(files).toEqual([]);
  });

  it('generates access.d.ts with Entitlement union', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [{ name: 'workspace', roles: ['admin', 'member'] }],
        entitlements: ['workspace:invite', 'workspace:manage'],
      },
    };
    const files = generator.generate(ir, { outputDir: '.vertz/generated', options: {} });
    expect(files).toHaveLength(1);
    expect(files[0]!.path).toBe('access.d.ts');

    const content = files[0]!.content;
    expect(content).toContain("type Entitlement = 'workspace:invite' | 'workspace:manage';");
  });

  it('generates ResourceType union from entity names', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [
          { name: 'workspace', roles: ['admin'] },
          { name: 'project', roles: ['manager'] },
        ],
        entitlements: ['workspace:invite'],
      },
    };
    const files = generator.generate(ir, { outputDir: '.vertz/generated', options: {} });
    const content = files[0]!.content;
    expect(content).toContain("type ResourceType = 'workspace' | 'project';");
  });

  it('generates Role<T> conditional type from entity roles', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [
          { name: 'workspace', roles: ['admin', 'member'] },
          { name: 'project', roles: ['manager', 'contributor', 'viewer'] },
        ],
        entitlements: ['workspace:invite'],
      },
    };
    const files = generator.generate(ir, { outputDir: '.vertz/generated', options: {} });
    const content = files[0]!.content;
    expect(content).toContain("T extends 'workspace' ? 'admin' | 'member'");
    expect(content).toContain("T extends 'project' ? 'manager' | 'contributor' | 'viewer'");
    expect(content).toContain('never;');
  });

  it('generates module augmentation for @vertz/server', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [],
        entitlements: ['post:view'],
      },
    };
    const files = generator.generate(ir, { outputDir: '.vertz/generated', options: {} });
    const content = files[0]!.content;
    expect(content).toContain("declare module '@vertz/server'");
    expect(content).toContain('can(entitlement: Entitlement');
    expect(content).toContain('check(entitlement: Entitlement');
    expect(content).toContain('authorize(entitlement: Entitlement');
  });

  it('generates module augmentation for @vertz/ui', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [],
        entitlements: ['post:view'],
      },
    };
    const files = generator.generate(ir, { outputDir: '.vertz/generated', options: {} });
    const content = files[0]!.content;
    expect(content).toContain("declare module '@vertz/ui'");
    expect(content).toContain("declare module '@vertz/ui/auth'");
  });

  it('generates file header', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [],
        entitlements: ['post:view'],
      },
    };
    const files = generator.generate(ir, { outputDir: '.vertz/generated', options: {} });
    const content = files[0]!.content;
    expect(content).toStartWith('// Generated by @vertz/codegen');
  });

  it('skips Role<T> when no entities have roles', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [],
        entitlements: ['global:admin'],
      },
    };
    const files = generator.generate(ir, { outputDir: '.vertz/generated', options: {} });
    const content = files[0]!.content;
    expect(content).not.toContain('type Role');
    expect(content).not.toContain('type ResourceType');
  });
});
