import { describe, expect, it } from 'bun:test';
import type { CodegenIR } from '../../types';
import { RlsPolicyGenerator } from '../rls-policy-generator';

function createEmptyIR(): CodegenIR {
  return {
    auth: { schemes: [], operations: [] },
    basePath: '/api',
    entities: [],
    modules: [],
    schemas: [],
  };
}

function getContent(generator: RlsPolicyGenerator, ir: CodegenIR): string {
  const files = generator.generate(ir, { outputDir: '.vertz/generated', options: {} });
  expect(files).toHaveLength(1);
  return files[0].content;
}

describe('RlsPolicyGenerator', () => {
  const generator = new RlsPolicyGenerator();

  it('returns no files when access is undefined', () => {
    const ir = createEmptyIR();
    const files = generator.generate(ir, { outputDir: '.vertz/generated', options: {} });
    expect(files).toEqual([]);
  });

  it('returns no files when no where clauses exist', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: { entities: [], entitlements: ['post:view'], whereClauses: [] },
    };
    const files = generator.generate(ir, { outputDir: '.vertz/generated', options: {} });
    expect(files).toEqual([]);
  });

  it('generates rls-policies.sql with file header', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [],
        entitlements: ['task:delete'],
        whereClauses: [
          {
            entitlement: 'task:delete',
            conditions: [{ kind: 'marker', column: 'createdBy', marker: 'user.id' }],
          },
        ],
      },
    };
    const content = getContent(generator, ir);
    expect(content).toStartWith('-- Generated by @vertz/codegen');
  });

  it('generates CREATE POLICY for user.id marker', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [],
        entitlements: ['task:delete'],
        whereClauses: [
          {
            entitlement: 'task:delete',
            conditions: [{ kind: 'marker', column: 'createdBy', marker: 'user.id' }],
          },
        ],
      },
    };
    const content = getContent(generator, ir);
    expect(content).toContain('-- Entitlement: task:delete');
    expect(content).toContain("created_by = current_setting('app.user_id')::UUID");
  });

  it('generates CREATE POLICY for user.tenantId marker', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [],
        entitlements: ['org:view'],
        whereClauses: [
          {
            entitlement: 'org:view',
            conditions: [{ kind: 'marker', column: 'orgId', marker: 'user.tenantId' }],
          },
        ],
      },
    };
    const content = getContent(generator, ir);
    expect(content).toContain("org_id = current_setting('app.tenant_id')::UUID");
  });

  it('generates equality conditions for literal values', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [],
        entitlements: ['task:view'],
        whereClauses: [
          {
            entitlement: 'task:view',
            conditions: [
              { kind: 'literal', column: 'archived', value: false },
              { kind: 'literal', column: 'status', value: 'active' },
            ],
          },
        ],
      },
    };
    const content = getContent(generator, ir);
    expect(content).toContain('archived = false');
    expect(content).toContain("status = 'active'");
  });

  it('generates numeric literal conditions', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [],
        entitlements: ['task:view'],
        whereClauses: [
          {
            entitlement: 'task:view',
            conditions: [{ kind: 'literal', column: 'priority', value: 1 }],
          },
        ],
      },
    };
    const content = getContent(generator, ir);
    expect(content).toContain('priority = 1');
  });

  it('converts camelCase column names to snake_case', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [],
        entitlements: ['task:edit'],
        whereClauses: [
          {
            entitlement: 'task:edit',
            conditions: [{ kind: 'marker', column: 'createdBy', marker: 'user.id' }],
          },
        ],
      },
    };
    const content = getContent(generator, ir);
    expect(content).toContain('created_by');
    expect(content).not.toContain('createdBy');
  });

  it('generates multiple policies for multiple entitlements', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [],
        entitlements: ['task:edit', 'task:delete'],
        whereClauses: [
          {
            entitlement: 'task:edit',
            conditions: [{ kind: 'marker', column: 'createdBy', marker: 'user.id' }],
          },
          {
            entitlement: 'task:delete',
            conditions: [{ kind: 'literal', column: 'archived', value: false }],
          },
        ],
      },
    };
    const content = getContent(generator, ir);
    expect(content).toContain('-- Entitlement: task:edit');
    expect(content).toContain('-- Entitlement: task:delete');
  });

  it('combines multiple conditions with AND', () => {
    const ir: CodegenIR = {
      ...createEmptyIR(),
      access: {
        entities: [],
        entitlements: ['task:edit'],
        whereClauses: [
          {
            entitlement: 'task:edit',
            conditions: [
              { kind: 'marker', column: 'createdBy', marker: 'user.id' },
              { kind: 'literal', column: 'archived', value: false },
            ],
          },
        ],
      },
    };
    const content = getContent(generator, ir);
    expect(content).toContain('AND');
  });
});
