import { isFetchValidationError, type Result } from '@vertz/fetch';
import { coerceFormDataToSchema, coerceLeaf } from '@vertz/schema';
import { computed, lifecycleEffect, signal } from '../runtime/signal';
import type { ReadonlySignal, Signal } from '../runtime/signal-types';
import { createFieldState, type FieldState } from './field-state';
import { formDataToObject } from './form-data';
import type { FormSchema } from './validation';
import { resolveFieldSchema, validate, validateField } from './validation';

const FIELD_STATE_SIGNALS = new Set(['error', 'dirty', 'touched', 'value']);
const FIELD_STATE_METHODS = new Set(['setValue', 'reset', 'setInitial']);

/**
 * An SDK method with endpoint metadata attached.
 * Generated SDK methods expose `.url` and `.method` for progressive enhancement.
 */
export interface SdkMethod<TBody, TResult> {
  (body: TBody): PromiseLike<Result<TResult, Error>>;
  url: string;
  method: string;
  meta?: { bodySchema?: FormSchema<TBody> };
}

/**
 * An SDK method with embedded schema metadata.
 * Generated by `@vertz/codegen` — carries `.meta.bodySchema` for auto-validation.
 */
export interface SdkMethodWithMeta<TBody, TResult> extends SdkMethod<TBody, TResult> {
  meta: { bodySchema: FormSchema<TBody> };
}

/** Reserved property names that cannot be used as field names on FormInstance. */
export type ReservedFormNames =
  | 'submitting'
  | 'dirty'
  | 'valid'
  | 'action'
  | 'method'
  | 'onSubmit'
  | 'reset'
  | 'setFieldError'
  | 'submit'
  | 'fields'
  | '__bindElement';

export type { FieldState };

/** Mapped type providing FieldState for each field in TBody (flat — no nested access). */
export type FieldAccessors<TBody> = { [K in keyof TBody]: FieldState<TBody[K]> };

/** Built-in object types that should NOT recurse into NestedFieldAccessors. */
type BuiltInObjects = Date | RegExp | File | Blob | Map<unknown, unknown> | Set<unknown>;

/** FieldState signal/method property names that conflict with nested field names. */
type FieldSignalReservedNames = 'error' | 'dirty' | 'touched' | 'value' | 'setValue' | 'reset';

/** Check if any key of T collides with FieldState property names. */
type HasReservedFieldName<T> = keyof T & FieldSignalReservedNames extends never ? false : true;

/** Recursive field accessors for nested schemas. */
export type NestedFieldAccessors<T> = {
  [K in keyof T]: T[K] extends BuiltInObjects
    ? FieldState<T[K]>
    : T[K] extends Array<infer U>
      ? FieldState<T[K]> & ArrayFieldAccessors<U>
      : T[K] extends Record<string, unknown>
        ? HasReservedFieldName<T[K]> extends true
          ? {
              __error: `Nested field name conflicts with FieldState property: ${keyof T[K] & FieldSignalReservedNames & string}`;
            }
          : FieldState<T[K]> & NestedFieldAccessors<T[K]>
        : FieldState<T[K]>;
};

/** Array field accessors — numeric index access to element-level fields. */
export type ArrayFieldAccessors<U> = {
  [index: number]: U extends BuiltInObjects
    ? FieldState<U>
    : U extends Record<string, unknown>
      ? FieldState<U> & NestedFieldAccessors<U>
      : FieldState<U>;
};

/** Deep partial utility for initial values. */
export type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends Array<infer U>
    ? Array<DeepPartial<U>>
    : T[K] extends Record<string, unknown>
      ? DeepPartial<T[K]>
      : T[K];
};

/** Union of all valid dot-paths through a nested type. */
export type FieldPath<T, Prefix extends string = ''> =
  | `${Prefix}${keyof T & string}`
  | {
      [K in keyof T & string]: T[K] extends Record<string, unknown>
        ? FieldPath<T[K], `${Prefix}${K}.`>
        : never;
    }[keyof T & string];

/** Mapped type providing typed field name strings for compile-time input validation. */
export type FieldNames<TBody> = { readonly [K in keyof TBody & string]: K };

/** Base properties available on every form instance. */
export interface FormBaseProperties<TBody> {
  action: string;
  method: string;
  onSubmit: (e: Event) => Promise<void>;
  reset: () => void;
  setFieldError: (field: FieldPath<TBody>, message: string) => void;
  submit: (formData?: FormData) => Promise<void>;
  submitting: Signal<boolean>;
  dirty: ReadonlySignal<boolean>;
  valid: ReadonlySignal<boolean>;
  fields: FieldNames<TBody>;
  __bindElement: (el: HTMLFormElement) => void;
}

/**
 * A form instance bound to an SDK method.
 * Combines base properties with per-field reactive state via Proxy.
 * If TBody has any key that conflicts with ReservedFormNames, it produces a type error.
 * TResult is used by form() overloads for return type inference.
 */
export type FormInstance<TBody, _TResult> = keyof TBody & ReservedFormNames extends never
  ? FormBaseProperties<TBody> & NestedFieldAccessors<TBody>
  : {
      __error: `Field name conflicts with reserved form property: ${keyof TBody & ReservedFormNames & string}`;
    };

/** Options for creating a form instance. */
export interface FormOptions<TBody, TResult> {
  /** Explicit schema for client-side validation before submission. */
  schema?: FormSchema<TBody>;
  /** Initial values for form fields. Supports nested partial values. */
  initial?: DeepPartial<TBody> | (() => DeepPartial<TBody>);
  /** Callback invoked after a successful submission. */
  onSuccess?: (result: TResult) => void;
  /** Callback invoked when validation or submission fails. */
  onError?: (errors: Record<string, string>) => void;
  /** When true, reset the form after a successful submission. */
  resetOnSuccess?: boolean;
  /**
   * Controls when fields with errors are re-validated after the first form submission.
   *
   * - `'blur'` (default) — Re-validates flagged fields when the user blurs them.
   * - `'change'` — Re-validates flagged fields on every input/change event.
   * - `'submit'` — No re-validation between submissions; errors only update on submit.
   *
   * Re-validation only activates after the first submit attempt. Fields without prior
   * errors are never re-validated on blur/change (no premature validation).
   */
  revalidateOn?: 'submit' | 'blur' | 'change';
}

/**
 * Create a form instance bound to an SDK method.
 *
 * The form provides direct properties for progressive enhancement (action, method, onSubmit),
 * per-field reactive state via Proxy, and submission handling with validation.
 *
 * When the SDK method has `.meta.bodySchema` (generated by `@vertz/codegen`),
 * the schema option is optional. When the SDK method lacks `.meta`, the schema option is required.
 */
export function form<TBody, TResult>(
  sdkMethod: SdkMethodWithMeta<TBody, TResult>,
  options?: FormOptions<TBody, TResult>,
): FormInstance<TBody, TResult>;
export function form<TBody, TResult>(
  sdkMethod: SdkMethod<TBody, TResult>,
  options: Required<Pick<FormOptions<TBody, TResult>, 'schema'>> & FormOptions<TBody, TResult>,
): FormInstance<TBody, TResult>;
export function form<TBody, TResult>(
  sdkMethod: SdkMethod<TBody, TResult>,
  options?: FormOptions<TBody, TResult>,
): FormInstance<TBody, TResult> {
  const fieldCache = new Map<string, FieldState>();
  const chainProxyCache = new Map<string, object>();
  const submitting = signal(false);
  // Generation counter — incremented when new fields are added to the cache.
  // Computed signals read this to re-evaluate when the field set changes.
  const fieldGeneration = signal(0);
  const revalidateOn = options?.revalidateOn ?? 'blur';
  let hasSubmitted = false;

  const dirty = computed(() => {
    fieldGeneration.value; // subscribe to field additions
    for (const field of fieldCache.values()) {
      if (field.dirty.value) return true;
    }
    return false;
  });

  const valid = computed(() => {
    fieldGeneration.value; // subscribe to field additions
    for (const field of fieldCache.values()) {
      if (field.error.value !== undefined) return false;
    }
    return true;
  });

  // When `initial` is a function, track its reactive dependencies so async
  // data (e.g. `() => query.data`) flows into the fields as it resolves.
  // A static value is used directly.
  const initialFn = typeof options?.initial === 'function' ? options.initial : undefined;
  let latestInitial: DeepPartial<TBody> | undefined =
    initialFn !== undefined ? initialFn() : (options?.initial as DeepPartial<TBody> | undefined);

  function resolveInitialFor(name: string): unknown {
    if (latestInitial == null) return undefined;
    const segments = name.includes('.') ? name.split('.') : [name];
    let current: unknown = latestInitial;
    for (const segment of segments) {
      if (current == null || typeof current !== 'object') return undefined;
      current = (current as Record<string, unknown>)[segment];
    }
    return current;
  }

  function getOrCreateField(name: string): FieldState {
    let field = fieldCache.get(name);
    if (!field) {
      field = createFieldState(name, resolveInitialFor(name));
      fieldCache.set(name, field);
      fieldGeneration.value++;
    }
    return field;
  }

  if (initialFn !== undefined) {
    lifecycleEffect(() => {
      latestInitial = initialFn();
      for (const [name, field] of fieldCache) {
        field.setInitial(resolveInitialFor(name));
      }
    });
  }

  function getOrCreateChainProxy(dotPath: string): object {
    let proxy = chainProxyCache.get(dotPath);
    if (proxy) return proxy;

    proxy = new Proxy(Object.create(null) as Record<string | symbol, unknown>, {
      get(_target, prop) {
        if (typeof prop === 'string') {
          if (FIELD_STATE_SIGNALS.has(prop)) {
            return getOrCreateField(dotPath)[prop as keyof FieldState];
          }
          if (FIELD_STATE_METHODS.has(prop)) {
            return getOrCreateField(dotPath)[prop as keyof FieldState];
          }
          const childPath = `${dotPath}.${prop}`;
          return getOrCreateChainProxy(childPath);
        }
        return undefined;
      },
    });

    chainProxyCache.set(dotPath, proxy);
    return proxy;
  }

  const resolvedSchema = options?.schema ?? sdkMethod.meta?.bodySchema;

  async function submitPipeline(formData: FormData): Promise<boolean> {
    // Lock against reentrant submissions (e.g. double-clicked submit button).
    // Set synchronously before any other work so a second sync call sees the guard.
    // Returns false when locked out so wrappers can skip post-processing.
    if (submitting.peek()) return false;
    submitting.value = true;
    try {
      hasSubmitted = true;
      const data = resolvedSchema
        ? coerceFormDataToSchema(formData, resolvedSchema)
        : formDataToObject(formData, { nested: true });

      if (resolvedSchema) {
        const result = validate(resolvedSchema, data);
        if (!result.success) {
          for (const [fieldName, message] of Object.entries(result.errors)) {
            getOrCreateField(fieldName).error.value = message;
          }
          options?.onError?.(result.errors);
          return true;
        }
      }

      // Clear previous errors
      for (const field of fieldCache.values()) {
        field.error.value = undefined;
      }

      const result = await sdkMethod(data as TBody);
      if (!result.ok) {
        if (isFetchValidationError(result.error)) {
          const fieldErrors: Record<string, string> = {};
          // First error per field wins — matches the shape of result.errors
          // produced by client-side validation above. Paths are already
          // normalized by the fetch client (empty → `_form`, arrays → dot-path).
          for (const { path, message } of result.error.errors) {
            if (fieldErrors[path] === undefined) {
              fieldErrors[path] = message;
            }
          }
          for (const [fieldName, message] of Object.entries(fieldErrors)) {
            getOrCreateField(fieldName).error.value = message;
          }
          options?.onError?.(fieldErrors);
          return true;
        }
        const message = result.error.message;
        getOrCreateField('_form').error.value = message;
        options?.onError?.({ _form: message });
        return true;
      }
      options?.onSuccess?.(result.data);

      if (options?.resetOnSuccess) {
        resetForm();
      }
    } finally {
      submitting.value = false;
    }
    return true;
  }

  let boundElement: HTMLFormElement | undefined;

  function resetForm(): void {
    hasSubmitted = false;
    for (const field of fieldCache.values()) {
      field.reset();
    }
  }

  function assembleFormData(): Record<string, unknown> {
    const result: Record<string, unknown> = {};
    for (const [name, f] of fieldCache) {
      const value = f.value.peek();
      if (!name.includes('.')) {
        result[name] = value;
        continue;
      }
      // Build nested object from dot-path key
      const segments = name.split('.');
      let current: Record<string, unknown> = result;
      for (let i = 0; i < segments.length - 1; i++) {
        const seg = segments[i]!;
        if (!(seg in current) || typeof current[seg] !== 'object' || current[seg] === null) {
          current[seg] = {};
        }
        current = current[seg] as Record<string, unknown>;
      }
      current[segments[segments.length - 1]!] = value;
    }
    return result;
  }

  function revalidateFieldIfNeeded(fieldName: string): void {
    if (!hasSubmitted || revalidateOn === 'submit' || !resolvedSchema) return;
    const field = fieldCache.get(fieldName);
    if (!field || field.error.peek() === undefined) return;

    const leafSchema = resolveFieldSchema(resolvedSchema, fieldName);
    const raw = field.value.peek();
    const coerced = leafSchema ? coerceLeaf(raw, leafSchema) : raw;
    const formData = assembleFormData();
    const result = validateField(resolvedSchema, fieldName, coerced, formData);
    field.error.value = result.valid ? undefined : result.error;
  }

  async function submitPipelineWithReset(formData: FormData): Promise<void> {
    const ran = await submitPipeline(formData);
    if (ran && options?.resetOnSuccess && boundElement) {
      // Only call reset on the element if submission succeeded (no error was set).
      // Check that there are no errors as a proxy for success.
      const hasErrors = [...fieldCache.values()].some((f) => f.error.peek() !== undefined);
      if (!hasErrors) {
        boundElement.reset();
      }
    }
  }

  function handleInputOrChange(e: Event): void {
    const target = e.target as HTMLInputElement | null;
    if (!target?.name) return;
    const field = getOrCreateField(target.name);
    field.setValue(target.value);
    if (revalidateOn === 'change') {
      revalidateFieldIfNeeded(target.name);
    }
  }

  function handleFocusout(e: Event): void {
    const target = e.target as HTMLInputElement | null;
    if (!target?.name) return;
    const field = getOrCreateField(target.name);
    field.touched.value = true;
    if (revalidateOn === 'blur') {
      revalidateFieldIfNeeded(target.name);
    }
  }

  const baseProperties: Record<string, unknown> = {
    action: sdkMethod.url,
    method: sdkMethod.method,
    onSubmit: async (e: Event) => {
      e.preventDefault();
      const formElement = e.target as HTMLFormElement;
      const formData = new FormData(formElement);
      const ran = await submitPipeline(formData);
      if (ran && options?.resetOnSuccess) {
        const hasErrors = [...fieldCache.values()].some((f) => f.error.peek() !== undefined);
        if (!hasErrors) {
          formElement.reset();
        }
      }
    },
    reset: resetForm,
    setFieldError: (field: string, message: string) => {
      getOrCreateField(field).error.value = message;
    },
    submit: async (formData?: FormData) => {
      if (formData) {
        const ran = await submitPipeline(formData);
        if (ran && options?.resetOnSuccess && boundElement) {
          const hasErrors = [...fieldCache.values()].some((f) => f.error.peek() !== undefined);
          if (!hasErrors) {
            boundElement.reset();
          }
        }
      } else if (boundElement) {
        await submitPipelineWithReset(new FormData(boundElement));
      }
    },
    submitting,
    dirty,
    valid,
    fields: new Proxy(Object.create(null) as Record<string, string>, {
      get(_target, prop) {
        if (typeof prop === 'string') return prop;
        return undefined;
      },
    }),
    __bindElement: (el: HTMLFormElement) => {
      boundElement = el;
      el.addEventListener('input', handleInputOrChange);
      el.addEventListener('change', handleInputOrChange);
      el.addEventListener('focusout', handleFocusout);
    },
  };

  const knownProperties = new Set(Object.keys(baseProperties));

  return new Proxy(baseProperties, {
    get(target, prop, receiver) {
      if (typeof prop === 'string') {
        if (knownProperties.has(prop)) {
          return target[prop];
        }
        return getOrCreateChainProxy(prop);
      }
      return Reflect.get(target, prop, receiver);
    },
  }) as FormInstance<TBody, TResult>;
}
